/**
 * AUTO-GENERATED by scripts/generate-hair-type-examples.mjs — do not edit by hand.
 *
 * One entry per hair-type example sitting in assets/hair-types/. Regenerate with:
 *
 *   npm run hair-types:sync
 *
 * (the generator and every `npm start` do it for you). Metro can only bundle an
 * asset some module requires by a literal path, which is why this file is code
 * rather than data — it is derived from the directory listing, holds no
 * judgement about any hair type, and is read only through
 * `hairTypeExample()` in src/lib/hairTypeExample.ts.
 *
 * These are the picker's texture examples, not catalog imagery: one head per
 * gender wearing the same plain hair in each of the four patterns, at the
 * length that gender wears it.
 * They are shown as generated and are never colour-graded.
 */

import type { Gender, HairTypeId } from './types';

/** What `require()` gives back for a bundled image: an asset registry handle. */
export type ExampleSource = number;

/** Keyed by gender, then hair type — both sides may be missing entries. */
export const hairTypeExamples: Partial<Record<Gender, Partial<Record<HairTypeId, ExampleSource>>>> = {};
