/**
 * AUTO-GENERATED by scripts/generate-mannequins.mjs — do not edit by hand.
 *
 * One entry per mannequin render sitting in assets/mannequins/. Regenerate with:
 *
 *   npm run mannequins:sync
 *
 * (every generator run and every `npm start` does it for you). Metro can only
 * bundle an asset some module requires by a literal path, which is why this file
 * is code rather than data — it is derived from the directory listing, holds no
 * judgement about any hairstyle, and is read only through
 * `mannequinRender()` in src/lib/mannequinRender.ts.
 *
 * These are the local, ahead-of-time catalog renders. The backend's own
 * `hairstyle.imageUrl` still wins over them when it is populated.
 */

import type { Gender, VariantId } from './types';
import type { ViewAngle } from '@/lib/hairShape';

/** What `require()` gives back for a bundled image: an asset registry handle. */
export type RenderSource = number;

export type MannequinRenderMap = Partial<Record<Gender, Partial<Record<ViewAngle, RenderSource>>>>;

/**
 * A style's renders, keyed by the variant of the hairstyle × hair type matrix
 * they were generated for. `any` is the single render that serves every type.
 * Which variant a given user should see is decided from the catalog by
 * `variantCandidates()` in src/lib/hairTypes.ts, never from this file.
 */
export type MannequinVariantMap = Partial<Record<VariantId, MannequinRenderMap>>;

/** Keyed by hairstyle id — the app never reads a name out of here. */
export const mannequinRenders: Record<string, MannequinVariantMap> = {
  'afro': {
    curly: {
      male: {
        front: require('../../assets/mannequins/afro/curly/male-front.png'),
        half: require('../../assets/mannequins/afro/curly/male-half.png'),
        side: require('../../assets/mannequins/afro/curly/male-side.png'),
        back: require('../../assets/mannequins/afro/curly/male-back.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/afro/coily/male-front.png'),
        half: require('../../assets/mannequins/afro/coily/male-half.png'),
        side: require('../../assets/mannequins/afro/coily/male-side.png'),
        back: require('../../assets/mannequins/afro/coily/male-back.png'),
      },
      female: {
        front: require('../../assets/mannequins/afro/coily/female-front.png'),
        half: require('../../assets/mannequins/afro/coily/female-half.png'),
        side: require('../../assets/mannequins/afro/coily/female-side.png'),
        back: require('../../assets/mannequins/afro/coily/female-back.png'),
      },
    },
  },
  'beach-waves': {
    any: {
      female: {
        front: require('../../assets/mannequins/beach-waves/any/female-front.png'),
        half: require('../../assets/mannequins/beach-waves/any/female-half.png'),
        side: require('../../assets/mannequins/beach-waves/any/female-side.png'),
        back: require('../../assets/mannequins/beach-waves/any/female-back.png'),
      },
    },
  },
  'blunt-bob': {
    coily: {
      female: {
        front: require('../../assets/mannequins/blunt-bob/coily/female-front.png'),
        half: require('../../assets/mannequins/blunt-bob/coily/female-half.png'),
        side: require('../../assets/mannequins/blunt-bob/coily/female-side.png'),
        back: require('../../assets/mannequins/blunt-bob/coily/female-back.png'),
      },
    },
  },
  'box-braids': {
    any: {
      male: {
        front: require('../../assets/mannequins/box-braids/any/male-front.png'),
        half: require('../../assets/mannequins/box-braids/any/male-half.png'),
        side: require('../../assets/mannequins/box-braids/any/male-side.png'),
        back: require('../../assets/mannequins/box-braids/any/male-back.png'),
      },
      female: {
        front: require('../../assets/mannequins/box-braids/any/female-front.png'),
        half: require('../../assets/mannequins/box-braids/any/female-half.png'),
        side: require('../../assets/mannequins/box-braids/any/female-side.png'),
        back: require('../../assets/mannequins/box-braids/any/female-back.png'),
      },
    },
  },
  'burst-fade': {
    wavy: {
      male: {
        front: require('../../assets/mannequins/burst-fade/wavy/male-front.png'),
        half: require('../../assets/mannequins/burst-fade/wavy/male-half.png'),
        side: require('../../assets/mannequins/burst-fade/wavy/male-side.png'),
        back: require('../../assets/mannequins/burst-fade/wavy/male-back.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/burst-fade/curly/male-front.png'),
        half: require('../../assets/mannequins/burst-fade/curly/male-half.png'),
        side: require('../../assets/mannequins/burst-fade/curly/male-side.png'),
        back: require('../../assets/mannequins/burst-fade/curly/male-back.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/burst-fade/coily/male-front.png'),
        half: require('../../assets/mannequins/burst-fade/coily/male-half.png'),
        side: require('../../assets/mannequins/burst-fade/coily/male-side.png'),
        back: require('../../assets/mannequins/burst-fade/coily/male-back.png'),
      },
    },
  },
  'butterfly-cut': {
    coily: {
      female: {
        front: require('../../assets/mannequins/butterfly-cut/coily/female-front.png'),
        half: require('../../assets/mannequins/butterfly-cut/coily/female-half.png'),
        side: require('../../assets/mannequins/butterfly-cut/coily/female-side.png'),
        back: require('../../assets/mannequins/butterfly-cut/coily/female-back.png'),
      },
    },
  },
  'buzz-cut': {
    any: {
      male: {
        front: require('../../assets/mannequins/buzz-cut/any/male-front.png'),
        half: require('../../assets/mannequins/buzz-cut/any/male-half.png'),
        side: require('../../assets/mannequins/buzz-cut/any/male-side.png'),
        back: require('../../assets/mannequins/buzz-cut/any/male-back.png'),
      },
      female: {
        front: require('../../assets/mannequins/buzz-cut/any/female-front.png'),
        half: require('../../assets/mannequins/buzz-cut/any/female-half.png'),
        side: require('../../assets/mannequins/buzz-cut/any/female-side.png'),
        back: require('../../assets/mannequins/buzz-cut/any/female-back.png'),
      },
    },
  },
  'caesar-cut': {
    straight: {
      male: {
        front: require('../../assets/mannequins/caesar-cut/straight/male-front.png'),
        half: require('../../assets/mannequins/caesar-cut/straight/male-half.png'),
        side: require('../../assets/mannequins/caesar-cut/straight/male-side.png'),
        back: require('../../assets/mannequins/caesar-cut/straight/male-back.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/caesar-cut/curly/male-front.png'),
        half: require('../../assets/mannequins/caesar-cut/curly/male-half.png'),
        side: require('../../assets/mannequins/caesar-cut/curly/male-side.png'),
        back: require('../../assets/mannequins/caesar-cut/curly/male-back.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/caesar-cut/coily/male-front.png'),
        half: require('../../assets/mannequins/caesar-cut/coily/male-half.png'),
        side: require('../../assets/mannequins/caesar-cut/coily/male-side.png'),
        back: require('../../assets/mannequins/caesar-cut/coily/male-back.png'),
      },
    },
  },
  'crew-cut': {
    straight: {
      male: {
        front: require('../../assets/mannequins/crew-cut/straight/male-front.png'),
        half: require('../../assets/mannequins/crew-cut/straight/male-half.png'),
        side: require('../../assets/mannequins/crew-cut/straight/male-side.png'),
        back: require('../../assets/mannequins/crew-cut/straight/male-back.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/crew-cut/curly/male-front.png'),
        half: require('../../assets/mannequins/crew-cut/curly/male-half.png'),
        side: require('../../assets/mannequins/crew-cut/curly/male-side.png'),
        back: require('../../assets/mannequins/crew-cut/curly/male-back.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/crew-cut/coily/male-front.png'),
        half: require('../../assets/mannequins/crew-cut/coily/male-half.png'),
        side: require('../../assets/mannequins/crew-cut/coily/male-side.png'),
        back: require('../../assets/mannequins/crew-cut/coily/male-back.png'),
      },
    },
  },
  'curly-shag': {
    coily: {
      female: {
        front: require('../../assets/mannequins/curly-shag/coily/female-front.png'),
        half: require('../../assets/mannequins/curly-shag/coily/female-half.png'),
        side: require('../../assets/mannequins/curly-shag/coily/female-side.png'),
        back: require('../../assets/mannequins/curly-shag/coily/female-back.png'),
      },
    },
  },
  'curly-top': {
    curly: {
      male: {
        front: require('../../assets/mannequins/curly-top/curly/male-front.png'),
        half: require('../../assets/mannequins/curly-top/curly/male-half.png'),
        side: require('../../assets/mannequins/curly-top/curly/male-side.png'),
        back: require('../../assets/mannequins/curly-top/curly/male-back.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/curly-top/coily/male-front.png'),
        half: require('../../assets/mannequins/curly-top/coily/male-half.png'),
        side: require('../../assets/mannequins/curly-top/coily/male-side.png'),
        back: require('../../assets/mannequins/curly-top/coily/male-back.png'),
      },
    },
  },
  'curtain-bangs': {
    wavy: {
      male: {
        front: require('../../assets/mannequins/curtain-bangs/wavy/male-front.png'),
        half: require('../../assets/mannequins/curtain-bangs/wavy/male-half.png'),
        side: require('../../assets/mannequins/curtain-bangs/wavy/male-side.png'),
        back: require('../../assets/mannequins/curtain-bangs/wavy/male-back.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/curtain-bangs/curly/male-front.png'),
        half: require('../../assets/mannequins/curtain-bangs/curly/male-half.png'),
        side: require('../../assets/mannequins/curtain-bangs/curly/male-side.png'),
        back: require('../../assets/mannequins/curtain-bangs/curly/male-back.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/curtain-bangs/coily/male-front.png'),
        half: require('../../assets/mannequins/curtain-bangs/coily/male-half.png'),
        side: require('../../assets/mannequins/curtain-bangs/coily/male-side.png'),
        back: require('../../assets/mannequins/curtain-bangs/coily/male-back.png'),
      },
      female: {
        front: require('../../assets/mannequins/curtain-bangs/coily/female-front.png'),
        half: require('../../assets/mannequins/curtain-bangs/coily/female-half.png'),
        side: require('../../assets/mannequins/curtain-bangs/coily/female-side.png'),
        back: require('../../assets/mannequins/curtain-bangs/coily/female-back.png'),
      },
    },
  },
  'french-crop': {
    straight: {
      male: {
        front: require('../../assets/mannequins/french-crop/straight/male-front.png'),
        half: require('../../assets/mannequins/french-crop/straight/male-half.png'),
        side: require('../../assets/mannequins/french-crop/straight/male-side.png'),
        back: require('../../assets/mannequins/french-crop/straight/male-back.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/french-crop/curly/male-front.png'),
        half: require('../../assets/mannequins/french-crop/curly/male-half.png'),
        side: require('../../assets/mannequins/french-crop/curly/male-side.png'),
        back: require('../../assets/mannequins/french-crop/curly/male-back.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/french-crop/coily/male-front.png'),
        half: require('../../assets/mannequins/french-crop/coily/male-half.png'),
        side: require('../../assets/mannequins/french-crop/coily/male-side.png'),
        back: require('../../assets/mannequins/french-crop/coily/male-back.png'),
      },
    },
  },
  'high-ponytail': {
    curly: {
      female: {
        front: require('../../assets/mannequins/high-ponytail/curly/female-front.png'),
        half: require('../../assets/mannequins/high-ponytail/curly/female-half.png'),
        side: require('../../assets/mannequins/high-ponytail/curly/female-side.png'),
        back: require('../../assets/mannequins/high-ponytail/curly/female-back.png'),
      },
    },
  },
  'high-skin-fade': {
    straight: {
      male: {
        front: require('../../assets/mannequins/high-skin-fade/straight/male-front.png'),
        half: require('../../assets/mannequins/high-skin-fade/straight/male-half.png'),
        side: require('../../assets/mannequins/high-skin-fade/straight/male-side.png'),
        back: require('../../assets/mannequins/high-skin-fade/straight/male-back.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/high-skin-fade/curly/male-front.png'),
        half: require('../../assets/mannequins/high-skin-fade/curly/male-half.png'),
        side: require('../../assets/mannequins/high-skin-fade/curly/male-side.png'),
        back: require('../../assets/mannequins/high-skin-fade/curly/male-back.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/high-skin-fade/coily/male-front.png'),
        half: require('../../assets/mannequins/high-skin-fade/coily/male-half.png'),
        side: require('../../assets/mannequins/high-skin-fade/coily/male-side.png'),
        back: require('../../assets/mannequins/high-skin-fade/coily/male-back.png'),
      },
    },
  },
  'ivy-league': {
    straight: {
      male: {
        front: require('../../assets/mannequins/ivy-league/straight/male-front.png'),
        half: require('../../assets/mannequins/ivy-league/straight/male-half.png'),
        side: require('../../assets/mannequins/ivy-league/straight/male-side.png'),
        back: require('../../assets/mannequins/ivy-league/straight/male-back.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/ivy-league/curly/male-front.png'),
        half: require('../../assets/mannequins/ivy-league/curly/male-half.png'),
        side: require('../../assets/mannequins/ivy-league/curly/male-side.png'),
        back: require('../../assets/mannequins/ivy-league/curly/male-back.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/ivy-league/coily/male-front.png'),
        half: require('../../assets/mannequins/ivy-league/coily/male-half.png'),
        side: require('../../assets/mannequins/ivy-league/coily/male-side.png'),
        back: require('../../assets/mannequins/ivy-league/coily/male-back.png'),
      },
    },
  },
  'long-layers': {
    coily: {
      female: {
        front: require('../../assets/mannequins/long-layers/coily/female-front.png'),
        half: require('../../assets/mannequins/long-layers/coily/female-half.png'),
        side: require('../../assets/mannequins/long-layers/coily/female-side.png'),
        back: require('../../assets/mannequins/long-layers/coily/female-back.png'),
      },
    },
  },
  'loose-curls': {
    any: {
      female: {
        front: require('../../assets/mannequins/loose-curls/any/female-front.png'),
        half: require('../../assets/mannequins/loose-curls/any/female-half.png'),
        side: require('../../assets/mannequins/loose-curls/any/female-side.png'),
        back: require('../../assets/mannequins/loose-curls/any/female-back.png'),
      },
    },
  },
  'low-taper-fade': {
    straight: {
      male: {
        front: require('../../assets/mannequins/low-taper-fade/straight/male-front.png'),
        half: require('../../assets/mannequins/low-taper-fade/straight/male-half.png'),
        side: require('../../assets/mannequins/low-taper-fade/straight/male-side.png'),
        back: require('../../assets/mannequins/low-taper-fade/straight/male-back.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/low-taper-fade/curly/male-front.png'),
        half: require('../../assets/mannequins/low-taper-fade/curly/male-half.png'),
        side: require('../../assets/mannequins/low-taper-fade/curly/male-side.png'),
        back: require('../../assets/mannequins/low-taper-fade/curly/male-back.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/low-taper-fade/coily/male-front.png'),
        half: require('../../assets/mannequins/low-taper-fade/coily/male-half.png'),
        side: require('../../assets/mannequins/low-taper-fade/coily/male-side.png'),
        back: require('../../assets/mannequins/low-taper-fade/coily/male-back.png'),
      },
    },
  },
  'man-bun': {
    straight: {
      male: {
        front: require('../../assets/mannequins/man-bun/straight/male-front.png'),
        half: require('../../assets/mannequins/man-bun/straight/male-half.png'),
        side: require('../../assets/mannequins/man-bun/straight/male-side.png'),
        back: require('../../assets/mannequins/man-bun/straight/male-back.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/man-bun/curly/male-front.png'),
        half: require('../../assets/mannequins/man-bun/curly/male-half.png'),
        side: require('../../assets/mannequins/man-bun/curly/male-side.png'),
        back: require('../../assets/mannequins/man-bun/curly/male-back.png'),
      },
    },
  },
  'messy-fringe': {
    wavy: {
      male: {
        front: require('../../assets/mannequins/messy-fringe/wavy/male-front.png'),
        half: require('../../assets/mannequins/messy-fringe/wavy/male-half.png'),
        side: require('../../assets/mannequins/messy-fringe/wavy/male-side.png'),
        back: require('../../assets/mannequins/messy-fringe/wavy/male-back.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/messy-fringe/curly/male-front.png'),
        half: require('../../assets/mannequins/messy-fringe/curly/male-half.png'),
        side: require('../../assets/mannequins/messy-fringe/curly/male-side.png'),
        back: require('../../assets/mannequins/messy-fringe/curly/male-back.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/messy-fringe/coily/male-front.png'),
        half: require('../../assets/mannequins/messy-fringe/coily/male-half.png'),
        side: require('../../assets/mannequins/messy-fringe/coily/male-side.png'),
        back: require('../../assets/mannequins/messy-fringe/coily/male-back.png'),
      },
      female: {
        front: require('../../assets/mannequins/messy-fringe/coily/female-front.png'),
        half: require('../../assets/mannequins/messy-fringe/coily/female-half.png'),
        side: require('../../assets/mannequins/messy-fringe/coily/female-side.png'),
        back: require('../../assets/mannequins/messy-fringe/coily/female-back.png'),
      },
    },
  },
  'mid-fade': {
    straight: {
      male: {
        front: require('../../assets/mannequins/mid-fade/straight/male-front.png'),
        half: require('../../assets/mannequins/mid-fade/straight/male-half.png'),
        side: require('../../assets/mannequins/mid-fade/straight/male-side.png'),
        back: require('../../assets/mannequins/mid-fade/straight/male-back.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/mid-fade/curly/male-front.png'),
        half: require('../../assets/mannequins/mid-fade/curly/male-half.png'),
        side: require('../../assets/mannequins/mid-fade/curly/male-side.png'),
        back: require('../../assets/mannequins/mid-fade/curly/male-back.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/mid-fade/coily/male-front.png'),
        half: require('../../assets/mannequins/mid-fade/coily/male-half.png'),
        side: require('../../assets/mannequins/mid-fade/coily/male-side.png'),
        back: require('../../assets/mannequins/mid-fade/coily/male-back.png'),
      },
    },
  },
  'modern-mullet': {
    wavy: {
      male: {
        front: require('../../assets/mannequins/modern-mullet/wavy/male-front.png'),
        half: require('../../assets/mannequins/modern-mullet/wavy/male-half.png'),
        side: require('../../assets/mannequins/modern-mullet/wavy/male-side.png'),
        back: require('../../assets/mannequins/modern-mullet/wavy/male-back.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/modern-mullet/curly/male-front.png'),
        half: require('../../assets/mannequins/modern-mullet/curly/male-half.png'),
        side: require('../../assets/mannequins/modern-mullet/curly/male-side.png'),
        back: require('../../assets/mannequins/modern-mullet/curly/male-back.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/modern-mullet/coily/male-front.png'),
        half: require('../../assets/mannequins/modern-mullet/coily/male-half.png'),
        side: require('../../assets/mannequins/modern-mullet/coily/male-side.png'),
        back: require('../../assets/mannequins/modern-mullet/coily/male-back.png'),
      },
      female: {
        front: require('../../assets/mannequins/modern-mullet/coily/female-front.png'),
        half: require('../../assets/mannequins/modern-mullet/coily/female-half.png'),
        side: require('../../assets/mannequins/modern-mullet/coily/female-side.png'),
        back: require('../../assets/mannequins/modern-mullet/coily/female-back.png'),
      },
    },
  },
  'mohawk': {
    straight: {
      male: {
        front: require('../../assets/mannequins/mohawk/straight/male-front.png'),
        half: require('../../assets/mannequins/mohawk/straight/male-half.png'),
        side: require('../../assets/mannequins/mohawk/straight/male-side.png'),
        back: require('../../assets/mannequins/mohawk/straight/male-back.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/mohawk/curly/male-front.png'),
        half: require('../../assets/mannequins/mohawk/curly/male-half.png'),
        side: require('../../assets/mannequins/mohawk/curly/male-side.png'),
        back: require('../../assets/mannequins/mohawk/curly/male-back.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/mohawk/coily/male-front.png'),
        half: require('../../assets/mannequins/mohawk/coily/male-half.png'),
        side: require('../../assets/mannequins/mohawk/coily/male-side.png'),
        back: require('../../assets/mannequins/mohawk/coily/male-back.png'),
      },
      female: {
        front: require('../../assets/mannequins/mohawk/coily/female-front.png'),
        half: require('../../assets/mannequins/mohawk/coily/female-half.png'),
        side: require('../../assets/mannequins/mohawk/coily/female-side.png'),
        back: require('../../assets/mannequins/mohawk/coily/female-back.png'),
      },
    },
  },
  'pixie-cut': {
    coily: {
      female: {
        front: require('../../assets/mannequins/pixie-cut/coily/female-front.png'),
        half: require('../../assets/mannequins/pixie-cut/coily/female-half.png'),
        side: require('../../assets/mannequins/pixie-cut/coily/female-side.png'),
        back: require('../../assets/mannequins/pixie-cut/coily/female-back.png'),
      },
    },
  },
  'pompadour': {
    straight: {
      male: {
        front: require('../../assets/mannequins/pompadour/straight/male-front.png'),
        half: require('../../assets/mannequins/pompadour/straight/male-half.png'),
        side: require('../../assets/mannequins/pompadour/straight/male-side.png'),
        back: require('../../assets/mannequins/pompadour/straight/male-back.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/pompadour/curly/male-front.png'),
        half: require('../../assets/mannequins/pompadour/curly/male-half.png'),
        side: require('../../assets/mannequins/pompadour/curly/male-side.png'),
        back: require('../../assets/mannequins/pompadour/curly/male-back.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/pompadour/coily/male-front.png'),
        half: require('../../assets/mannequins/pompadour/coily/male-half.png'),
        side: require('../../assets/mannequins/pompadour/coily/male-side.png'),
        back: require('../../assets/mannequins/pompadour/coily/male-back.png'),
      },
    },
  },
  'quiff': {
    wavy: {
      male: {
        front: require('../../assets/mannequins/quiff/wavy/male-front.png'),
        half: require('../../assets/mannequins/quiff/wavy/male-half.png'),
        side: require('../../assets/mannequins/quiff/wavy/male-side.png'),
        back: require('../../assets/mannequins/quiff/wavy/male-back.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/quiff/curly/male-front.png'),
        half: require('../../assets/mannequins/quiff/curly/male-half.png'),
        side: require('../../assets/mannequins/quiff/curly/male-side.png'),
        back: require('../../assets/mannequins/quiff/curly/male-back.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/quiff/coily/male-front.png'),
        half: require('../../assets/mannequins/quiff/coily/male-half.png'),
        side: require('../../assets/mannequins/quiff/coily/male-side.png'),
        back: require('../../assets/mannequins/quiff/coily/male-back.png'),
      },
    },
  },
  'shoulder-flow': {
    wavy: {
      male: {
        front: require('../../assets/mannequins/shoulder-flow/wavy/male-front.png'),
        half: require('../../assets/mannequins/shoulder-flow/wavy/male-half.png'),
        side: require('../../assets/mannequins/shoulder-flow/wavy/male-side.png'),
        back: require('../../assets/mannequins/shoulder-flow/wavy/male-back.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/shoulder-flow/curly/male-front.png'),
        half: require('../../assets/mannequins/shoulder-flow/curly/male-half.png'),
        side: require('../../assets/mannequins/shoulder-flow/curly/male-side.png'),
        back: require('../../assets/mannequins/shoulder-flow/curly/male-back.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/shoulder-flow/coily/male-front.png'),
        half: require('../../assets/mannequins/shoulder-flow/coily/male-half.png'),
        side: require('../../assets/mannequins/shoulder-flow/coily/male-side.png'),
        back: require('../../assets/mannequins/shoulder-flow/coily/male-back.png'),
      },
    },
  },
  'side-part': {
    straight: {
      male: {
        front: require('../../assets/mannequins/side-part/straight/male-front.png'),
        half: require('../../assets/mannequins/side-part/straight/male-half.png'),
        side: require('../../assets/mannequins/side-part/straight/male-side.png'),
        back: require('../../assets/mannequins/side-part/straight/male-back.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/side-part/curly/male-front.png'),
        half: require('../../assets/mannequins/side-part/curly/male-half.png'),
        side: require('../../assets/mannequins/side-part/curly/male-side.png'),
        back: require('../../assets/mannequins/side-part/curly/male-back.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/side-part/coily/male-front.png'),
        half: require('../../assets/mannequins/side-part/coily/male-half.png'),
        side: require('../../assets/mannequins/side-part/coily/male-side.png'),
        back: require('../../assets/mannequins/side-part/coily/male-back.png'),
      },
    },
  },
  'sleek-straight': {
    any: {
      female: {
        front: require('../../assets/mannequins/sleek-straight/any/female-front.png'),
        half: require('../../assets/mannequins/sleek-straight/any/female-half.png'),
        side: require('../../assets/mannequins/sleek-straight/any/female-side.png'),
        back: require('../../assets/mannequins/sleek-straight/any/female-back.png'),
      },
    },
  },
  'slick-back': {
    straight: {
      male: {
        front: require('../../assets/mannequins/slick-back/straight/male-front.png'),
        half: require('../../assets/mannequins/slick-back/straight/male-half.png'),
        side: require('../../assets/mannequins/slick-back/straight/male-side.png'),
        back: require('../../assets/mannequins/slick-back/straight/male-back.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/slick-back/curly/male-front.png'),
        half: require('../../assets/mannequins/slick-back/curly/male-half.png'),
        side: require('../../assets/mannequins/slick-back/curly/male-side.png'),
        back: require('../../assets/mannequins/slick-back/curly/male-back.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/slick-back/coily/male-front.png'),
        half: require('../../assets/mannequins/slick-back/coily/male-half.png'),
        side: require('../../assets/mannequins/slick-back/coily/male-side.png'),
        back: require('../../assets/mannequins/slick-back/coily/male-back.png'),
      },
    },
  },
  'textured-crop': {
    wavy: {
      male: {
        front: require('../../assets/mannequins/textured-crop/wavy/male-front.png'),
        half: require('../../assets/mannequins/textured-crop/wavy/male-half.png'),
        side: require('../../assets/mannequins/textured-crop/wavy/male-side.png'),
        back: require('../../assets/mannequins/textured-crop/wavy/male-back.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/textured-crop/curly/male-front.png'),
        half: require('../../assets/mannequins/textured-crop/curly/male-half.png'),
        side: require('../../assets/mannequins/textured-crop/curly/male-side.png'),
        back: require('../../assets/mannequins/textured-crop/curly/male-back.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/textured-crop/coily/male-front.png'),
        half: require('../../assets/mannequins/textured-crop/coily/male-half.png'),
        side: require('../../assets/mannequins/textured-crop/coily/male-side.png'),
        back: require('../../assets/mannequins/textured-crop/coily/male-back.png'),
      },
    },
  },
  'textured-lob': {
    coily: {
      female: {
        front: require('../../assets/mannequins/textured-lob/coily/female-front.png'),
        half: require('../../assets/mannequins/textured-lob/coily/female-half.png'),
        side: require('../../assets/mannequins/textured-lob/coily/female-side.png'),
        back: require('../../assets/mannequins/textured-lob/coily/female-back.png'),
      },
    },
  },
  'top-knot': {
    straight: {
      male: {
        front: require('../../assets/mannequins/top-knot/straight/male-front.png'),
        half: require('../../assets/mannequins/top-knot/straight/male-half.png'),
        side: require('../../assets/mannequins/top-knot/straight/male-side.png'),
        back: require('../../assets/mannequins/top-knot/straight/male-back.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/top-knot/curly/male-front.png'),
        half: require('../../assets/mannequins/top-knot/curly/male-half.png'),
        side: require('../../assets/mannequins/top-knot/curly/male-side.png'),
        back: require('../../assets/mannequins/top-knot/curly/male-back.png'),
      },
      female: {
        front: require('../../assets/mannequins/top-knot/curly/female-front.png'),
        half: require('../../assets/mannequins/top-knot/curly/female-half.png'),
        side: require('../../assets/mannequins/top-knot/curly/female-side.png'),
        back: require('../../assets/mannequins/top-knot/curly/female-back.png'),
      },
    },
  },
  'twist-out': {
    curly: {
      male: {
        front: require('../../assets/mannequins/twist-out/curly/male-front.png'),
        half: require('../../assets/mannequins/twist-out/curly/male-half.png'),
        side: require('../../assets/mannequins/twist-out/curly/male-side.png'),
        back: require('../../assets/mannequins/twist-out/curly/male-back.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/twist-out/coily/male-front.png'),
        half: require('../../assets/mannequins/twist-out/coily/male-half.png'),
        side: require('../../assets/mannequins/twist-out/coily/male-side.png'),
        back: require('../../assets/mannequins/twist-out/coily/male-back.png'),
      },
      female: {
        front: require('../../assets/mannequins/twist-out/coily/female-front.png'),
        half: require('../../assets/mannequins/twist-out/coily/female-half.png'),
        side: require('../../assets/mannequins/twist-out/coily/female-side.png'),
        back: require('../../assets/mannequins/twist-out/coily/female-back.png'),
      },
    },
  },
  'wolf-cut': {
    wavy: {
      male: {
        front: require('../../assets/mannequins/wolf-cut/wavy/male-front.png'),
        half: require('../../assets/mannequins/wolf-cut/wavy/male-half.png'),
        side: require('../../assets/mannequins/wolf-cut/wavy/male-side.png'),
        back: require('../../assets/mannequins/wolf-cut/wavy/male-back.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/wolf-cut/curly/male-front.png'),
        half: require('../../assets/mannequins/wolf-cut/curly/male-half.png'),
        side: require('../../assets/mannequins/wolf-cut/curly/male-side.png'),
        back: require('../../assets/mannequins/wolf-cut/curly/male-back.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/wolf-cut/coily/male-front.png'),
        half: require('../../assets/mannequins/wolf-cut/coily/male-half.png'),
        side: require('../../assets/mannequins/wolf-cut/coily/male-side.png'),
        back: require('../../assets/mannequins/wolf-cut/coily/male-back.png'),
      },
      female: {
        front: require('../../assets/mannequins/wolf-cut/coily/female-front.png'),
        half: require('../../assets/mannequins/wolf-cut/coily/female-half.png'),
        side: require('../../assets/mannequins/wolf-cut/coily/female-side.png'),
        back: require('../../assets/mannequins/wolf-cut/coily/female-back.png'),
      },
    },
  },
};

/**
 * The matching hair masks: greyscale, white where the haircut is, the same size
 * as the render they belong to. Written by `scripts/generate-hair-masks.mjs`
 * and used to keep the colour grade off the mannequin. A render missing from
 * here is graded whole, which is the old behaviour rather than a broken one.
 */
export const mannequinMasks: Record<string, MannequinVariantMap> = {
  'afro': {
    curly: {
      male: {
        front: require('../../assets/mannequins/afro/curly/male-front-mask.png'),
        half: require('../../assets/mannequins/afro/curly/male-half-mask.png'),
        side: require('../../assets/mannequins/afro/curly/male-side-mask.png'),
        back: require('../../assets/mannequins/afro/curly/male-back-mask.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/afro/coily/male-front-mask.png'),
        half: require('../../assets/mannequins/afro/coily/male-half-mask.png'),
        side: require('../../assets/mannequins/afro/coily/male-side-mask.png'),
        back: require('../../assets/mannequins/afro/coily/male-back-mask.png'),
      },
      female: {
        front: require('../../assets/mannequins/afro/coily/female-front-mask.png'),
        half: require('../../assets/mannequins/afro/coily/female-half-mask.png'),
        side: require('../../assets/mannequins/afro/coily/female-side-mask.png'),
        back: require('../../assets/mannequins/afro/coily/female-back-mask.png'),
      },
    },
  },
  'beach-waves': {
    any: {
      female: {
        front: require('../../assets/mannequins/beach-waves/any/female-front-mask.png'),
        half: require('../../assets/mannequins/beach-waves/any/female-half-mask.png'),
        side: require('../../assets/mannequins/beach-waves/any/female-side-mask.png'),
        back: require('../../assets/mannequins/beach-waves/any/female-back-mask.png'),
      },
    },
  },
  'blunt-bob': {
    coily: {
      female: {
        front: require('../../assets/mannequins/blunt-bob/coily/female-front-mask.png'),
        half: require('../../assets/mannequins/blunt-bob/coily/female-half-mask.png'),
        side: require('../../assets/mannequins/blunt-bob/coily/female-side-mask.png'),
        back: require('../../assets/mannequins/blunt-bob/coily/female-back-mask.png'),
      },
    },
  },
  'box-braids': {
    any: {
      male: {
        front: require('../../assets/mannequins/box-braids/any/male-front-mask.png'),
        half: require('../../assets/mannequins/box-braids/any/male-half-mask.png'),
        side: require('../../assets/mannequins/box-braids/any/male-side-mask.png'),
        back: require('../../assets/mannequins/box-braids/any/male-back-mask.png'),
      },
      female: {
        front: require('../../assets/mannequins/box-braids/any/female-front-mask.png'),
        half: require('../../assets/mannequins/box-braids/any/female-half-mask.png'),
        side: require('../../assets/mannequins/box-braids/any/female-side-mask.png'),
        back: require('../../assets/mannequins/box-braids/any/female-back-mask.png'),
      },
    },
  },
  'burst-fade': {
    wavy: {
      male: {
        front: require('../../assets/mannequins/burst-fade/wavy/male-front-mask.png'),
        half: require('../../assets/mannequins/burst-fade/wavy/male-half-mask.png'),
        side: require('../../assets/mannequins/burst-fade/wavy/male-side-mask.png'),
        back: require('../../assets/mannequins/burst-fade/wavy/male-back-mask.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/burst-fade/curly/male-front-mask.png'),
        half: require('../../assets/mannequins/burst-fade/curly/male-half-mask.png'),
        side: require('../../assets/mannequins/burst-fade/curly/male-side-mask.png'),
        back: require('../../assets/mannequins/burst-fade/curly/male-back-mask.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/burst-fade/coily/male-front-mask.png'),
        half: require('../../assets/mannequins/burst-fade/coily/male-half-mask.png'),
        side: require('../../assets/mannequins/burst-fade/coily/male-side-mask.png'),
        back: require('../../assets/mannequins/burst-fade/coily/male-back-mask.png'),
      },
    },
  },
  'butterfly-cut': {
    coily: {
      female: {
        front: require('../../assets/mannequins/butterfly-cut/coily/female-front-mask.png'),
        half: require('../../assets/mannequins/butterfly-cut/coily/female-half-mask.png'),
        side: require('../../assets/mannequins/butterfly-cut/coily/female-side-mask.png'),
        back: require('../../assets/mannequins/butterfly-cut/coily/female-back-mask.png'),
      },
    },
  },
  'buzz-cut': {
    any: {
      male: {
        front: require('../../assets/mannequins/buzz-cut/any/male-front-mask.png'),
        half: require('../../assets/mannequins/buzz-cut/any/male-half-mask.png'),
        side: require('../../assets/mannequins/buzz-cut/any/male-side-mask.png'),
        back: require('../../assets/mannequins/buzz-cut/any/male-back-mask.png'),
      },
      female: {
        front: require('../../assets/mannequins/buzz-cut/any/female-front-mask.png'),
        half: require('../../assets/mannequins/buzz-cut/any/female-half-mask.png'),
        side: require('../../assets/mannequins/buzz-cut/any/female-side-mask.png'),
        back: require('../../assets/mannequins/buzz-cut/any/female-back-mask.png'),
      },
    },
  },
  'caesar-cut': {
    straight: {
      male: {
        front: require('../../assets/mannequins/caesar-cut/straight/male-front-mask.png'),
        half: require('../../assets/mannequins/caesar-cut/straight/male-half-mask.png'),
        side: require('../../assets/mannequins/caesar-cut/straight/male-side-mask.png'),
        back: require('../../assets/mannequins/caesar-cut/straight/male-back-mask.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/caesar-cut/curly/male-front-mask.png'),
        half: require('../../assets/mannequins/caesar-cut/curly/male-half-mask.png'),
        side: require('../../assets/mannequins/caesar-cut/curly/male-side-mask.png'),
        back: require('../../assets/mannequins/caesar-cut/curly/male-back-mask.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/caesar-cut/coily/male-front-mask.png'),
        half: require('../../assets/mannequins/caesar-cut/coily/male-half-mask.png'),
        side: require('../../assets/mannequins/caesar-cut/coily/male-side-mask.png'),
        back: require('../../assets/mannequins/caesar-cut/coily/male-back-mask.png'),
      },
    },
  },
  'crew-cut': {
    straight: {
      male: {
        front: require('../../assets/mannequins/crew-cut/straight/male-front-mask.png'),
        half: require('../../assets/mannequins/crew-cut/straight/male-half-mask.png'),
        side: require('../../assets/mannequins/crew-cut/straight/male-side-mask.png'),
        back: require('../../assets/mannequins/crew-cut/straight/male-back-mask.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/crew-cut/curly/male-front-mask.png'),
        half: require('../../assets/mannequins/crew-cut/curly/male-half-mask.png'),
        side: require('../../assets/mannequins/crew-cut/curly/male-side-mask.png'),
        back: require('../../assets/mannequins/crew-cut/curly/male-back-mask.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/crew-cut/coily/male-front-mask.png'),
        half: require('../../assets/mannequins/crew-cut/coily/male-half-mask.png'),
        side: require('../../assets/mannequins/crew-cut/coily/male-side-mask.png'),
        back: require('../../assets/mannequins/crew-cut/coily/male-back-mask.png'),
      },
    },
  },
  'curly-shag': {
    coily: {
      female: {
        front: require('../../assets/mannequins/curly-shag/coily/female-front-mask.png'),
        half: require('../../assets/mannequins/curly-shag/coily/female-half-mask.png'),
        side: require('../../assets/mannequins/curly-shag/coily/female-side-mask.png'),
        back: require('../../assets/mannequins/curly-shag/coily/female-back-mask.png'),
      },
    },
  },
  'curly-top': {
    curly: {
      male: {
        front: require('../../assets/mannequins/curly-top/curly/male-front-mask.png'),
        half: require('../../assets/mannequins/curly-top/curly/male-half-mask.png'),
        side: require('../../assets/mannequins/curly-top/curly/male-side-mask.png'),
        back: require('../../assets/mannequins/curly-top/curly/male-back-mask.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/curly-top/coily/male-front-mask.png'),
        half: require('../../assets/mannequins/curly-top/coily/male-half-mask.png'),
        side: require('../../assets/mannequins/curly-top/coily/male-side-mask.png'),
        back: require('../../assets/mannequins/curly-top/coily/male-back-mask.png'),
      },
    },
  },
  'curtain-bangs': {
    wavy: {
      male: {
        front: require('../../assets/mannequins/curtain-bangs/wavy/male-front-mask.png'),
        half: require('../../assets/mannequins/curtain-bangs/wavy/male-half-mask.png'),
        side: require('../../assets/mannequins/curtain-bangs/wavy/male-side-mask.png'),
        back: require('../../assets/mannequins/curtain-bangs/wavy/male-back-mask.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/curtain-bangs/curly/male-front-mask.png'),
        half: require('../../assets/mannequins/curtain-bangs/curly/male-half-mask.png'),
        side: require('../../assets/mannequins/curtain-bangs/curly/male-side-mask.png'),
        back: require('../../assets/mannequins/curtain-bangs/curly/male-back-mask.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/curtain-bangs/coily/male-front-mask.png'),
        half: require('../../assets/mannequins/curtain-bangs/coily/male-half-mask.png'),
        side: require('../../assets/mannequins/curtain-bangs/coily/male-side-mask.png'),
        back: require('../../assets/mannequins/curtain-bangs/coily/male-back-mask.png'),
      },
      female: {
        front: require('../../assets/mannequins/curtain-bangs/coily/female-front-mask.png'),
        half: require('../../assets/mannequins/curtain-bangs/coily/female-half-mask.png'),
        side: require('../../assets/mannequins/curtain-bangs/coily/female-side-mask.png'),
        back: require('../../assets/mannequins/curtain-bangs/coily/female-back-mask.png'),
      },
    },
  },
  'french-crop': {
    straight: {
      male: {
        front: require('../../assets/mannequins/french-crop/straight/male-front-mask.png'),
        half: require('../../assets/mannequins/french-crop/straight/male-half-mask.png'),
        side: require('../../assets/mannequins/french-crop/straight/male-side-mask.png'),
        back: require('../../assets/mannequins/french-crop/straight/male-back-mask.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/french-crop/curly/male-front-mask.png'),
        half: require('../../assets/mannequins/french-crop/curly/male-half-mask.png'),
        side: require('../../assets/mannequins/french-crop/curly/male-side-mask.png'),
        back: require('../../assets/mannequins/french-crop/curly/male-back-mask.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/french-crop/coily/male-front-mask.png'),
        half: require('../../assets/mannequins/french-crop/coily/male-half-mask.png'),
        side: require('../../assets/mannequins/french-crop/coily/male-side-mask.png'),
        back: require('../../assets/mannequins/french-crop/coily/male-back-mask.png'),
      },
    },
  },
  'high-ponytail': {
    curly: {
      female: {
        front: require('../../assets/mannequins/high-ponytail/curly/female-front-mask.png'),
        half: require('../../assets/mannequins/high-ponytail/curly/female-half-mask.png'),
        side: require('../../assets/mannequins/high-ponytail/curly/female-side-mask.png'),
        back: require('../../assets/mannequins/high-ponytail/curly/female-back-mask.png'),
      },
    },
  },
  'high-skin-fade': {
    straight: {
      male: {
        front: require('../../assets/mannequins/high-skin-fade/straight/male-front-mask.png'),
        half: require('../../assets/mannequins/high-skin-fade/straight/male-half-mask.png'),
        side: require('../../assets/mannequins/high-skin-fade/straight/male-side-mask.png'),
        back: require('../../assets/mannequins/high-skin-fade/straight/male-back-mask.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/high-skin-fade/curly/male-front-mask.png'),
        half: require('../../assets/mannequins/high-skin-fade/curly/male-half-mask.png'),
        side: require('../../assets/mannequins/high-skin-fade/curly/male-side-mask.png'),
        back: require('../../assets/mannequins/high-skin-fade/curly/male-back-mask.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/high-skin-fade/coily/male-front-mask.png'),
        half: require('../../assets/mannequins/high-skin-fade/coily/male-half-mask.png'),
        side: require('../../assets/mannequins/high-skin-fade/coily/male-side-mask.png'),
        back: require('../../assets/mannequins/high-skin-fade/coily/male-back-mask.png'),
      },
    },
  },
  'ivy-league': {
    straight: {
      male: {
        front: require('../../assets/mannequins/ivy-league/straight/male-front-mask.png'),
        half: require('../../assets/mannequins/ivy-league/straight/male-half-mask.png'),
        side: require('../../assets/mannequins/ivy-league/straight/male-side-mask.png'),
        back: require('../../assets/mannequins/ivy-league/straight/male-back-mask.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/ivy-league/curly/male-front-mask.png'),
        half: require('../../assets/mannequins/ivy-league/curly/male-half-mask.png'),
        side: require('../../assets/mannequins/ivy-league/curly/male-side-mask.png'),
        back: require('../../assets/mannequins/ivy-league/curly/male-back-mask.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/ivy-league/coily/male-front-mask.png'),
        half: require('../../assets/mannequins/ivy-league/coily/male-half-mask.png'),
        side: require('../../assets/mannequins/ivy-league/coily/male-side-mask.png'),
        back: require('../../assets/mannequins/ivy-league/coily/male-back-mask.png'),
      },
    },
  },
  'long-layers': {
    coily: {
      female: {
        front: require('../../assets/mannequins/long-layers/coily/female-front-mask.png'),
        half: require('../../assets/mannequins/long-layers/coily/female-half-mask.png'),
        side: require('../../assets/mannequins/long-layers/coily/female-side-mask.png'),
        back: require('../../assets/mannequins/long-layers/coily/female-back-mask.png'),
      },
    },
  },
  'loose-curls': {
    any: {
      female: {
        front: require('../../assets/mannequins/loose-curls/any/female-front-mask.png'),
        half: require('../../assets/mannequins/loose-curls/any/female-half-mask.png'),
        side: require('../../assets/mannequins/loose-curls/any/female-side-mask.png'),
        back: require('../../assets/mannequins/loose-curls/any/female-back-mask.png'),
      },
    },
  },
  'low-taper-fade': {
    straight: {
      male: {
        front: require('../../assets/mannequins/low-taper-fade/straight/male-front-mask.png'),
        half: require('../../assets/mannequins/low-taper-fade/straight/male-half-mask.png'),
        side: require('../../assets/mannequins/low-taper-fade/straight/male-side-mask.png'),
        back: require('../../assets/mannequins/low-taper-fade/straight/male-back-mask.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/low-taper-fade/curly/male-front-mask.png'),
        half: require('../../assets/mannequins/low-taper-fade/curly/male-half-mask.png'),
        side: require('../../assets/mannequins/low-taper-fade/curly/male-side-mask.png'),
        back: require('../../assets/mannequins/low-taper-fade/curly/male-back-mask.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/low-taper-fade/coily/male-front-mask.png'),
        half: require('../../assets/mannequins/low-taper-fade/coily/male-half-mask.png'),
        side: require('../../assets/mannequins/low-taper-fade/coily/male-side-mask.png'),
        back: require('../../assets/mannequins/low-taper-fade/coily/male-back-mask.png'),
      },
    },
  },
  'man-bun': {
    straight: {
      male: {
        front: require('../../assets/mannequins/man-bun/straight/male-front-mask.png'),
        half: require('../../assets/mannequins/man-bun/straight/male-half-mask.png'),
        side: require('../../assets/mannequins/man-bun/straight/male-side-mask.png'),
        back: require('../../assets/mannequins/man-bun/straight/male-back-mask.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/man-bun/curly/male-front-mask.png'),
        half: require('../../assets/mannequins/man-bun/curly/male-half-mask.png'),
        side: require('../../assets/mannequins/man-bun/curly/male-side-mask.png'),
        back: require('../../assets/mannequins/man-bun/curly/male-back-mask.png'),
      },
    },
  },
  'messy-fringe': {
    wavy: {
      male: {
        front: require('../../assets/mannequins/messy-fringe/wavy/male-front-mask.png'),
        half: require('../../assets/mannequins/messy-fringe/wavy/male-half-mask.png'),
        side: require('../../assets/mannequins/messy-fringe/wavy/male-side-mask.png'),
        back: require('../../assets/mannequins/messy-fringe/wavy/male-back-mask.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/messy-fringe/curly/male-front-mask.png'),
        half: require('../../assets/mannequins/messy-fringe/curly/male-half-mask.png'),
        side: require('../../assets/mannequins/messy-fringe/curly/male-side-mask.png'),
        back: require('../../assets/mannequins/messy-fringe/curly/male-back-mask.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/messy-fringe/coily/male-front-mask.png'),
        half: require('../../assets/mannequins/messy-fringe/coily/male-half-mask.png'),
        side: require('../../assets/mannequins/messy-fringe/coily/male-side-mask.png'),
        back: require('../../assets/mannequins/messy-fringe/coily/male-back-mask.png'),
      },
      female: {
        front: require('../../assets/mannequins/messy-fringe/coily/female-front-mask.png'),
        half: require('../../assets/mannequins/messy-fringe/coily/female-half-mask.png'),
        side: require('../../assets/mannequins/messy-fringe/coily/female-side-mask.png'),
        back: require('../../assets/mannequins/messy-fringe/coily/female-back-mask.png'),
      },
    },
  },
  'mid-fade': {
    straight: {
      male: {
        front: require('../../assets/mannequins/mid-fade/straight/male-front-mask.png'),
        half: require('../../assets/mannequins/mid-fade/straight/male-half-mask.png'),
        side: require('../../assets/mannequins/mid-fade/straight/male-side-mask.png'),
        back: require('../../assets/mannequins/mid-fade/straight/male-back-mask.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/mid-fade/curly/male-front-mask.png'),
        half: require('../../assets/mannequins/mid-fade/curly/male-half-mask.png'),
        side: require('../../assets/mannequins/mid-fade/curly/male-side-mask.png'),
        back: require('../../assets/mannequins/mid-fade/curly/male-back-mask.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/mid-fade/coily/male-front-mask.png'),
        half: require('../../assets/mannequins/mid-fade/coily/male-half-mask.png'),
        side: require('../../assets/mannequins/mid-fade/coily/male-side-mask.png'),
        back: require('../../assets/mannequins/mid-fade/coily/male-back-mask.png'),
      },
    },
  },
  'modern-mullet': {
    wavy: {
      male: {
        front: require('../../assets/mannequins/modern-mullet/wavy/male-front-mask.png'),
        half: require('../../assets/mannequins/modern-mullet/wavy/male-half-mask.png'),
        side: require('../../assets/mannequins/modern-mullet/wavy/male-side-mask.png'),
        back: require('../../assets/mannequins/modern-mullet/wavy/male-back-mask.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/modern-mullet/curly/male-front-mask.png'),
        half: require('../../assets/mannequins/modern-mullet/curly/male-half-mask.png'),
        side: require('../../assets/mannequins/modern-mullet/curly/male-side-mask.png'),
        back: require('../../assets/mannequins/modern-mullet/curly/male-back-mask.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/modern-mullet/coily/male-front-mask.png'),
        half: require('../../assets/mannequins/modern-mullet/coily/male-half-mask.png'),
        side: require('../../assets/mannequins/modern-mullet/coily/male-side-mask.png'),
        back: require('../../assets/mannequins/modern-mullet/coily/male-back-mask.png'),
      },
      female: {
        front: require('../../assets/mannequins/modern-mullet/coily/female-front-mask.png'),
        half: require('../../assets/mannequins/modern-mullet/coily/female-half-mask.png'),
        side: require('../../assets/mannequins/modern-mullet/coily/female-side-mask.png'),
        back: require('../../assets/mannequins/modern-mullet/coily/female-back-mask.png'),
      },
    },
  },
  'mohawk': {
    straight: {
      male: {
        front: require('../../assets/mannequins/mohawk/straight/male-front-mask.png'),
        half: require('../../assets/mannequins/mohawk/straight/male-half-mask.png'),
        side: require('../../assets/mannequins/mohawk/straight/male-side-mask.png'),
        back: require('../../assets/mannequins/mohawk/straight/male-back-mask.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/mohawk/curly/male-front-mask.png'),
        half: require('../../assets/mannequins/mohawk/curly/male-half-mask.png'),
        side: require('../../assets/mannequins/mohawk/curly/male-side-mask.png'),
        back: require('../../assets/mannequins/mohawk/curly/male-back-mask.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/mohawk/coily/male-front-mask.png'),
        half: require('../../assets/mannequins/mohawk/coily/male-half-mask.png'),
        side: require('../../assets/mannequins/mohawk/coily/male-side-mask.png'),
        back: require('../../assets/mannequins/mohawk/coily/male-back-mask.png'),
      },
      female: {
        front: require('../../assets/mannequins/mohawk/coily/female-front-mask.png'),
        half: require('../../assets/mannequins/mohawk/coily/female-half-mask.png'),
        side: require('../../assets/mannequins/mohawk/coily/female-side-mask.png'),
        back: require('../../assets/mannequins/mohawk/coily/female-back-mask.png'),
      },
    },
  },
  'pixie-cut': {
    coily: {
      female: {
        front: require('../../assets/mannequins/pixie-cut/coily/female-front-mask.png'),
        half: require('../../assets/mannequins/pixie-cut/coily/female-half-mask.png'),
        side: require('../../assets/mannequins/pixie-cut/coily/female-side-mask.png'),
        back: require('../../assets/mannequins/pixie-cut/coily/female-back-mask.png'),
      },
    },
  },
  'pompadour': {
    straight: {
      male: {
        front: require('../../assets/mannequins/pompadour/straight/male-front-mask.png'),
        half: require('../../assets/mannequins/pompadour/straight/male-half-mask.png'),
        side: require('../../assets/mannequins/pompadour/straight/male-side-mask.png'),
        back: require('../../assets/mannequins/pompadour/straight/male-back-mask.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/pompadour/curly/male-front-mask.png'),
        half: require('../../assets/mannequins/pompadour/curly/male-half-mask.png'),
        side: require('../../assets/mannequins/pompadour/curly/male-side-mask.png'),
        back: require('../../assets/mannequins/pompadour/curly/male-back-mask.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/pompadour/coily/male-front-mask.png'),
        half: require('../../assets/mannequins/pompadour/coily/male-half-mask.png'),
        side: require('../../assets/mannequins/pompadour/coily/male-side-mask.png'),
        back: require('../../assets/mannequins/pompadour/coily/male-back-mask.png'),
      },
    },
  },
  'quiff': {
    wavy: {
      male: {
        front: require('../../assets/mannequins/quiff/wavy/male-front-mask.png'),
        half: require('../../assets/mannequins/quiff/wavy/male-half-mask.png'),
        side: require('../../assets/mannequins/quiff/wavy/male-side-mask.png'),
        back: require('../../assets/mannequins/quiff/wavy/male-back-mask.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/quiff/curly/male-front-mask.png'),
        half: require('../../assets/mannequins/quiff/curly/male-half-mask.png'),
        side: require('../../assets/mannequins/quiff/curly/male-side-mask.png'),
        back: require('../../assets/mannequins/quiff/curly/male-back-mask.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/quiff/coily/male-front-mask.png'),
        half: require('../../assets/mannequins/quiff/coily/male-half-mask.png'),
        side: require('../../assets/mannequins/quiff/coily/male-side-mask.png'),
        back: require('../../assets/mannequins/quiff/coily/male-back-mask.png'),
      },
    },
  },
  'shoulder-flow': {
    wavy: {
      male: {
        front: require('../../assets/mannequins/shoulder-flow/wavy/male-front-mask.png'),
        half: require('../../assets/mannequins/shoulder-flow/wavy/male-half-mask.png'),
        side: require('../../assets/mannequins/shoulder-flow/wavy/male-side-mask.png'),
        back: require('../../assets/mannequins/shoulder-flow/wavy/male-back-mask.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/shoulder-flow/curly/male-front-mask.png'),
        half: require('../../assets/mannequins/shoulder-flow/curly/male-half-mask.png'),
        side: require('../../assets/mannequins/shoulder-flow/curly/male-side-mask.png'),
        back: require('../../assets/mannequins/shoulder-flow/curly/male-back-mask.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/shoulder-flow/coily/male-front-mask.png'),
        half: require('../../assets/mannequins/shoulder-flow/coily/male-half-mask.png'),
        side: require('../../assets/mannequins/shoulder-flow/coily/male-side-mask.png'),
        back: require('../../assets/mannequins/shoulder-flow/coily/male-back-mask.png'),
      },
    },
  },
  'side-part': {
    straight: {
      male: {
        front: require('../../assets/mannequins/side-part/straight/male-front-mask.png'),
        half: require('../../assets/mannequins/side-part/straight/male-half-mask.png'),
        side: require('../../assets/mannequins/side-part/straight/male-side-mask.png'),
        back: require('../../assets/mannequins/side-part/straight/male-back-mask.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/side-part/curly/male-front-mask.png'),
        half: require('../../assets/mannequins/side-part/curly/male-half-mask.png'),
        side: require('../../assets/mannequins/side-part/curly/male-side-mask.png'),
        back: require('../../assets/mannequins/side-part/curly/male-back-mask.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/side-part/coily/male-front-mask.png'),
        half: require('../../assets/mannequins/side-part/coily/male-half-mask.png'),
        side: require('../../assets/mannequins/side-part/coily/male-side-mask.png'),
        back: require('../../assets/mannequins/side-part/coily/male-back-mask.png'),
      },
    },
  },
  'sleek-straight': {
    any: {
      female: {
        front: require('../../assets/mannequins/sleek-straight/any/female-front-mask.png'),
        half: require('../../assets/mannequins/sleek-straight/any/female-half-mask.png'),
        side: require('../../assets/mannequins/sleek-straight/any/female-side-mask.png'),
        back: require('../../assets/mannequins/sleek-straight/any/female-back-mask.png'),
      },
    },
  },
  'slick-back': {
    straight: {
      male: {
        front: require('../../assets/mannequins/slick-back/straight/male-front-mask.png'),
        half: require('../../assets/mannequins/slick-back/straight/male-half-mask.png'),
        side: require('../../assets/mannequins/slick-back/straight/male-side-mask.png'),
        back: require('../../assets/mannequins/slick-back/straight/male-back-mask.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/slick-back/curly/male-front-mask.png'),
        half: require('../../assets/mannequins/slick-back/curly/male-half-mask.png'),
        side: require('../../assets/mannequins/slick-back/curly/male-side-mask.png'),
        back: require('../../assets/mannequins/slick-back/curly/male-back-mask.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/slick-back/coily/male-front-mask.png'),
        half: require('../../assets/mannequins/slick-back/coily/male-half-mask.png'),
        side: require('../../assets/mannequins/slick-back/coily/male-side-mask.png'),
        back: require('../../assets/mannequins/slick-back/coily/male-back-mask.png'),
      },
    },
  },
  'textured-crop': {
    wavy: {
      male: {
        front: require('../../assets/mannequins/textured-crop/wavy/male-front-mask.png'),
        half: require('../../assets/mannequins/textured-crop/wavy/male-half-mask.png'),
        side: require('../../assets/mannequins/textured-crop/wavy/male-side-mask.png'),
        back: require('../../assets/mannequins/textured-crop/wavy/male-back-mask.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/textured-crop/curly/male-front-mask.png'),
        half: require('../../assets/mannequins/textured-crop/curly/male-half-mask.png'),
        side: require('../../assets/mannequins/textured-crop/curly/male-side-mask.png'),
        back: require('../../assets/mannequins/textured-crop/curly/male-back-mask.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/textured-crop/coily/male-front-mask.png'),
        half: require('../../assets/mannequins/textured-crop/coily/male-half-mask.png'),
        side: require('../../assets/mannequins/textured-crop/coily/male-side-mask.png'),
        back: require('../../assets/mannequins/textured-crop/coily/male-back-mask.png'),
      },
    },
  },
  'textured-lob': {
    coily: {
      female: {
        front: require('../../assets/mannequins/textured-lob/coily/female-front-mask.png'),
        half: require('../../assets/mannequins/textured-lob/coily/female-half-mask.png'),
        side: require('../../assets/mannequins/textured-lob/coily/female-side-mask.png'),
        back: require('../../assets/mannequins/textured-lob/coily/female-back-mask.png'),
      },
    },
  },
  'top-knot': {
    straight: {
      male: {
        front: require('../../assets/mannequins/top-knot/straight/male-front-mask.png'),
        half: require('../../assets/mannequins/top-knot/straight/male-half-mask.png'),
        side: require('../../assets/mannequins/top-knot/straight/male-side-mask.png'),
        back: require('../../assets/mannequins/top-knot/straight/male-back-mask.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/top-knot/curly/male-front-mask.png'),
        half: require('../../assets/mannequins/top-knot/curly/male-half-mask.png'),
        side: require('../../assets/mannequins/top-knot/curly/male-side-mask.png'),
        back: require('../../assets/mannequins/top-knot/curly/male-back-mask.png'),
      },
      female: {
        front: require('../../assets/mannequins/top-knot/curly/female-front-mask.png'),
        half: require('../../assets/mannequins/top-knot/curly/female-half-mask.png'),
        side: require('../../assets/mannequins/top-knot/curly/female-side-mask.png'),
        back: require('../../assets/mannequins/top-knot/curly/female-back-mask.png'),
      },
    },
  },
  'twist-out': {
    curly: {
      male: {
        front: require('../../assets/mannequins/twist-out/curly/male-front-mask.png'),
        half: require('../../assets/mannequins/twist-out/curly/male-half-mask.png'),
        side: require('../../assets/mannequins/twist-out/curly/male-side-mask.png'),
        back: require('../../assets/mannequins/twist-out/curly/male-back-mask.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/twist-out/coily/male-front-mask.png'),
        half: require('../../assets/mannequins/twist-out/coily/male-half-mask.png'),
        side: require('../../assets/mannequins/twist-out/coily/male-side-mask.png'),
        back: require('../../assets/mannequins/twist-out/coily/male-back-mask.png'),
      },
      female: {
        front: require('../../assets/mannequins/twist-out/coily/female-front-mask.png'),
        half: require('../../assets/mannequins/twist-out/coily/female-half-mask.png'),
        side: require('../../assets/mannequins/twist-out/coily/female-side-mask.png'),
        back: require('../../assets/mannequins/twist-out/coily/female-back-mask.png'),
      },
    },
  },
  'wolf-cut': {
    wavy: {
      male: {
        front: require('../../assets/mannequins/wolf-cut/wavy/male-front-mask.png'),
        half: require('../../assets/mannequins/wolf-cut/wavy/male-half-mask.png'),
        side: require('../../assets/mannequins/wolf-cut/wavy/male-side-mask.png'),
        back: require('../../assets/mannequins/wolf-cut/wavy/male-back-mask.png'),
      },
    },
    curly: {
      male: {
        front: require('../../assets/mannequins/wolf-cut/curly/male-front-mask.png'),
        half: require('../../assets/mannequins/wolf-cut/curly/male-half-mask.png'),
        side: require('../../assets/mannequins/wolf-cut/curly/male-side-mask.png'),
        back: require('../../assets/mannequins/wolf-cut/curly/male-back-mask.png'),
      },
    },
    coily: {
      male: {
        front: require('../../assets/mannequins/wolf-cut/coily/male-front-mask.png'),
        half: require('../../assets/mannequins/wolf-cut/coily/male-half-mask.png'),
        side: require('../../assets/mannequins/wolf-cut/coily/male-side-mask.png'),
        back: require('../../assets/mannequins/wolf-cut/coily/male-back-mask.png'),
      },
      female: {
        front: require('../../assets/mannequins/wolf-cut/coily/female-front-mask.png'),
        half: require('../../assets/mannequins/wolf-cut/coily/female-half-mask.png'),
        side: require('../../assets/mannequins/wolf-cut/coily/female-side-mask.png'),
        back: require('../../assets/mannequins/wolf-cut/coily/female-back-mask.png'),
      },
    },
  },
};
