/**
 * AUTO-GENERATED by scripts/generate-mannequins.mjs — do not edit by hand.
 *
 * One entry per mannequin render sitting in assets/mannequins/. Regenerate with:
 *
 *   npm run mannequins:sync
 *
 * (every generator run and every `npm start` does it for you). Metro can only
 * bundle an asset some module requires by a literal path, which is why this file
 * is code rather than data — it is derived from the directory listing, holds no
 * judgement about any hairstyle, and is read only through
 * `mannequinRender()` in src/lib/mannequinRender.ts.
 *
 * These are the local, ahead-of-time catalog renders. The backend's own
 * `hairstyle.imageUrl` still wins over them when it is populated.
 */

import type { Gender, HairLengthId, VariantId } from './types';
import type { ViewAngle } from '@/lib/hairShape';

/** What `require()` gives back for a bundled image: an asset registry handle. */
export type RenderSource = number;

export type MannequinRenderMap = Partial<Record<Gender, Partial<Record<ViewAngle, RenderSource>>>>;

/**
 * A variant's renders, keyed by length. `medium` is the anchor — the cut as the
 * catalog authored it — and it is the only length most styles have, because most
 * styles carry no `lengths` row at all. On disk the anchor sits loose in the
 * variant directory and only `short` and `long` are nested; that asymmetry is
 * deliberate and is explained in scripts/lib/renders.mjs.
 */
export type MannequinLengthMap = Partial<Record<HairLengthId, MannequinRenderMap>>;

/**
 * A style's renders, keyed by the variant of the hairstyle × hair type matrix
 * they were generated for. `any` is the single render that serves every type.
 * Which variant a given user should see is decided from the catalog by
 * `variantCandidates()` in src/lib/hairTypes.ts, never from this file.
 */
export type MannequinVariantMap = Partial<Record<VariantId, MannequinLengthMap>>;

/** Keyed by hairstyle id — the app never reads a name out of here. */
export const mannequinRenders: Record<string, MannequinVariantMap> = {};

/**
 * The matching hair masks: greyscale, white where the haircut is, the same size
 * as the render they belong to. Written by `scripts/generate-hair-masks.mjs`
 * and used to keep the colour grade off the mannequin. A render missing from
 * here is graded whole, which is the old behaviour rather than a broken one.
 */
export const mannequinMasks: Record<string, MannequinVariantMap> = {};
