/**
 * Placeholder catalog.
 *
 * Stands in for the `GET /catalog` response the Node API will serve from the
 * Railway database. Everything here is data: adding a style or a category must
 * never require touching a screen.
 */

import type { Catalog, Category, HairColor, Hairstyle, HairShape, TextureKind } from './types';

const categories: Category[] = [
  { id: 'short', name: 'Short Cuts', tagline: 'Clean, sharp and low effort', icon: 'cut-outline', genders: ['male', 'female'], order: 1 },
  { id: 'medium', name: 'Medium Cuts', tagline: 'Versatile everyday lengths', icon: 'layers-outline', genders: ['male', 'female'], order: 2 },
  { id: 'long', name: 'Long Hair', tagline: 'Flow, layers and movement', icon: 'water-outline', genders: ['male', 'female'], order: 3 },
  { id: 'curly', name: 'Curly', tagline: 'Coils, curls and volume', icon: 'sync-outline', genders: ['male', 'female'], order: 4 },
  { id: 'wavy', name: 'Wavy', tagline: 'Soft, natural bends', icon: 'pulse-outline', genders: ['male', 'female'], order: 5 },
  { id: 'straight', name: 'Straight', tagline: 'Sleek and polished', icon: 'remove-outline', genders: ['male', 'female'], order: 6 },
  { id: 'fades', name: 'Fades', tagline: 'Tapers, skins and blends', icon: 'trending-down-outline', genders: ['male', 'female'], order: 7 },
  { id: 'updo', name: 'Braids & Updos', tagline: 'Tied back and out of the way', icon: 'git-merge-outline', genders: ['male', 'female'], order: 8 },
  { id: 'trendy', name: 'Trending', tagline: 'What people are asking for now', icon: 'flame-outline', genders: ['male', 'female'], order: 9 },
];

const colors: HairColor[] = [
  { id: 'jet', name: 'Jet Black', hex: '#171313', shade: '#000000' },
  { id: 'espresso', name: 'Espresso', hex: '#33231B', shade: '#1C120C' },
  { id: 'chestnut', name: 'Chestnut', hex: '#5E3D26', shade: '#3B2415' },
  { id: 'auburn', name: 'Auburn', hex: '#8A4326', shade: '#5E2B16' },
  { id: 'caramel', name: 'Caramel', hex: '#A9743F', shade: '#7A4E26' },
  { id: 'honey', name: 'Honey Blonde', hex: '#C9A063', shade: '#9C7740' },
  { id: 'platinum', name: 'Platinum', hex: '#DDD3C4', shade: '#B3A897' },
  { id: 'ash', name: 'Ash Grey', hex: '#9C978F', shade: '#726D66' },
  { id: 'silver', name: 'Silver Fox', hex: '#C6C7C9', shade: '#9B9CA0' },
  { id: 'smoke', name: 'Smoke Blue', hex: '#5C6E86', shade: '#3E4B5C' },
  { id: 'rose', name: 'Rose Gold', hex: '#C08A8A', shade: '#966465' },
  { id: 'burgundy', name: 'Burgundy', hex: '#6B2438', shade: '#471523' },
];

/** Shorthand so the style table below stays readable. */
const shape = (
  top: number,
  sides: number,
  back: number,
  fringe: number,
  texture: TextureKind,
  extra: Partial<HairShape> = {},
): HairShape => ({ top, sides, back, fringe, texture, ...extra });

type Row = Omit<Hairstyle, 'imageUrl'>;

const hairstyles: Row[] = [
  {
    id: 'buzz-cut',
    name: 'Buzz Cut',
    categoryIds: ['short', 'straight'],
    genders: ['male', 'female'],
    tags: ['low maintenance', 'summer', 'classic'],
    description: 'A single clipper length all over. Nothing to style and nothing to hide behind, so it lives or dies on your head shape.',
    maintenance: 'Low',
    bestFor: ['Oval', 'Square'],
    popularity: 78,
    adjustments: ['length', 'color'],
    shape: shape(0.06, 0.1, 0, 0.08, 'straight'),
    defaultColorId: 'espresso',
  },
  {
    id: 'crew-cut',
    name: 'Crew Cut',
    categoryIds: ['short', 'straight'],
    genders: ['male'],
    tags: ['classic', 'office', 'easy'],
    description: 'Short and tapered on the sides with a little length left on top. The default good haircut.',
    maintenance: 'Low',
    bestFor: ['Oval', 'Round', 'Square'],
    popularity: 84,
    adjustments: ['length', 'fade', 'color'],
    shape: shape(0.2, 0.16, 0, 0.15, 'straight'),
    defaultColorId: 'espresso',
  },
  {
    id: 'textured-crop',
    name: 'Textured Crop',
    categoryIds: ['short', 'trendy', 'fades'],
    genders: ['male'],
    tags: ['modern', 'messy', 'popular'],
    description: 'Choppy, matte texture on top pushed forward into a short fringe, with tight sides.',
    maintenance: 'Medium',
    bestFor: ['Oval', 'Long'],
    popularity: 93,
    adjustments: ['length', 'fade', 'color'],
    shape: shape(0.33, 0.14, 0, 0.45, 'spiky'),
    defaultColorId: 'chestnut',
  },
  {
    id: 'french-crop',
    name: 'French Crop',
    categoryIds: ['short', 'fades'],
    genders: ['male'],
    tags: ['fringe', 'sharp', 'european'],
    description: 'A blunt, straight fringe sitting on the forehead with faded sides. Clean lines, very little upkeep.',
    maintenance: 'Low',
    bestFor: ['Oval', 'Square'],
    popularity: 81,
    adjustments: ['fade', 'color'],
    shape: shape(0.24, 0.12, 0, 0.62, 'straight'),
    defaultColorId: 'jet',
  },
  {
    id: 'caesar-cut',
    name: 'Caesar Cut',
    categoryIds: ['short', 'straight'],
    genders: ['male'],
    tags: ['fringe', 'retro'],
    description: 'Short, horizontally cut fringe combed forward. Forgiving on a receding hairline.',
    maintenance: 'Low',
    bestFor: ['Round', 'Oval'],
    popularity: 62,
    adjustments: ['length', 'color'],
    shape: shape(0.18, 0.18, 0, 0.55, 'straight'),
    defaultColorId: 'espresso',
  },
  {
    id: 'ivy-league',
    name: 'Ivy League',
    categoryIds: ['short', 'medium', 'straight'],
    genders: ['male'],
    tags: ['smart', 'side part', 'office'],
    description: 'A crew cut grown out enough to take a side part. Smart without looking fussy.',
    maintenance: 'Medium',
    bestFor: ['Oval', 'Square'],
    popularity: 70,
    adjustments: ['length', 'fade', 'color'],
    shape: shape(0.3, 0.2, 0, 0.3, 'straight', { part: 'side' }),
    defaultColorId: 'chestnut',
  },
  {
    id: 'low-taper-fade',
    name: 'Low Taper Fade',
    categoryIds: ['fades', 'short', 'trendy'],
    genders: ['male'],
    tags: ['barber favourite', 'clean', 'sharp'],
    description: 'The fade starts low, just above the ear, and blends gradually. Subtle enough for any setting.',
    maintenance: 'High',
    bestFor: ['Oval', 'Round', 'Heart'],
    popularity: 97,
    adjustments: ['length', 'fade', 'color'],
    shape: shape(0.36, 0.13, 0, 0.35, 'curly'),
    defaultColorId: 'espresso',
  },
  {
    id: 'mid-fade',
    name: 'Mid Fade',
    categoryIds: ['fades', 'short'],
    genders: ['male'],
    tags: ['balanced', 'sharp'],
    description: 'A fade that starts halfway up the side. The safe middle ground between low and high.',
    maintenance: 'High',
    bestFor: ['Oval', 'Square'],
    popularity: 90,
    adjustments: ['length', 'fade', 'color'],
    shape: shape(0.34, 0.09, 0, 0.3, 'straight'),
    defaultColorId: 'jet',
  },
  {
    id: 'high-skin-fade',
    name: 'High Skin Fade',
    categoryIds: ['fades', 'trendy'],
    genders: ['male'],
    tags: ['bold', 'contrast', 'sharp'],
    description: 'Skin at the bottom climbing high up the side for maximum contrast against the top.',
    maintenance: 'High',
    bestFor: ['Oval', 'Long'],
    popularity: 88,
    adjustments: ['length', 'fade', 'color'],
    shape: shape(0.42, 0.04, 0, 0.3, 'straight'),
    defaultColorId: 'jet',
  },
  {
    id: 'burst-fade',
    name: 'Burst Fade',
    categoryIds: ['fades', 'trendy', 'curly'],
    genders: ['male'],
    tags: ['curly friendly', 'street'],
    description: 'The fade radiates around the ear and leaves weight at the back. Made for curly and coily hair.',
    maintenance: 'High',
    bestFor: ['Oval', 'Diamond'],
    popularity: 86,
    adjustments: ['fade', 'color'],
    shape: shape(0.48, 0.1, 0.06, 0.32, 'coily'),
    defaultColorId: 'jet',
  },
  {
    id: 'quiff',
    name: 'Quiff',
    categoryIds: ['medium', 'trendy'],
    genders: ['male'],
    tags: ['volume', 'night out'],
    description: 'Length at the front lifted up and back into a soft peak. Needs a blow dryer to look right.',
    maintenance: 'High',
    bestFor: ['Square', 'Oval', 'Round'],
    popularity: 85,
    adjustments: ['length', 'fade', 'color'],
    shape: shape(0.68, 0.22, 0, 0.06, 'wavy'),
    defaultColorId: 'chestnut',
  },
  {
    id: 'pompadour',
    name: 'Pompadour',
    categoryIds: ['medium', 'trendy'],
    genders: ['male'],
    tags: ['retro', 'volume', 'statement'],
    description: 'Big, swept-back volume at the front held high off the forehead. A commitment.',
    maintenance: 'High',
    bestFor: ['Oval', 'Square'],
    popularity: 74,
    adjustments: ['length', 'fade', 'color'],
    shape: shape(0.85, 0.2, 0, 0.02, 'straight'),
    defaultColorId: 'jet',
  },
  {
    id: 'side-part',
    name: 'Classic Side Part',
    categoryIds: ['medium', 'straight'],
    genders: ['male'],
    tags: ['timeless', 'office'],
    description: 'A hard or natural parting with the bulk combed to one side. Always appropriate.',
    maintenance: 'Medium',
    bestFor: ['Oval', 'Round', 'Heart'],
    popularity: 76,
    adjustments: ['length', 'fade', 'color'],
    shape: shape(0.4, 0.24, 0, 0.22, 'straight', { part: 'side' }),
    defaultColorId: 'chestnut',
  },
  {
    id: 'messy-fringe',
    name: 'Messy Fringe',
    categoryIds: ['medium', 'trendy'],
    genders: ['male', 'female'],
    tags: ['casual', 'youthful'],
    description: 'Loose, undone length falling forward over the brow. Deliberately unstructured.',
    maintenance: 'Low',
    bestFor: ['Oval', 'Long'],
    popularity: 82,
    adjustments: ['length', 'color'],
    shape: shape(0.42, 0.32, 0.04, 0.78, 'wavy'),
    defaultColorId: 'caramel',
  },
  {
    id: 'curtain-bangs',
    name: 'Curtain Bangs',
    categoryIds: ['medium', 'wavy', 'trendy'],
    genders: ['female', 'male'],
    tags: ['soft', 'face framing'],
    description: 'A centre-parted fringe that sweeps away on both sides to frame the face.',
    maintenance: 'Medium',
    bestFor: ['Round', 'Square', 'Heart'],
    popularity: 94,
    adjustments: ['length', 'color'],
    shape: shape(0.3, 0.6, 0.55, 0.55, 'wavy', { part: 'middle' }),
    defaultColorId: 'caramel',
  },
  {
    id: 'blunt-bob',
    name: 'Blunt Bob',
    categoryIds: ['medium', 'straight', 'trendy'],
    genders: ['female'],
    tags: ['sharp', 'chic'],
    description: 'One length, cut clean at the jaw with no layers. Graphic and very deliberate.',
    maintenance: 'Medium',
    bestFor: ['Oval', 'Heart'],
    popularity: 91,
    adjustments: ['length', 'color'],
    shape: shape(0.22, 0.72, 0.3, 0.35, 'straight'),
    defaultColorId: 'jet',
  },
  {
    id: 'textured-lob',
    name: 'Textured Lob',
    categoryIds: ['medium', 'wavy'],
    genders: ['female'],
    tags: ['easy', 'everyday'],
    description: 'A long bob with soft internal layers, sitting just past the collarbone.',
    maintenance: 'Low',
    bestFor: ['Oval', 'Round', 'Square'],
    popularity: 89,
    adjustments: ['length', 'color'],
    shape: shape(0.28, 0.85, 0.5, 0.3, 'wavy', { part: 'middle' }),
    defaultColorId: 'chestnut',
  },
  {
    id: 'pixie-cut',
    name: 'Pixie Cut',
    categoryIds: ['short', 'trendy'],
    genders: ['female'],
    tags: ['bold', 'low effort'],
    description: 'Cropped close at the back and sides with textured length left on top.',
    maintenance: 'Medium',
    bestFor: ['Heart', 'Oval'],
    popularity: 79,
    adjustments: ['length', 'color'],
    shape: shape(0.38, 0.24, 0.02, 0.5, 'spiky', { part: 'side' }),
    defaultColorId: 'platinum',
  },
  {
    id: 'long-layers',
    name: 'Long Layers',
    categoryIds: ['long', 'straight'],
    genders: ['female'],
    tags: ['movement', 'classic'],
    description: 'Length kept long with layers cut through the mid-lengths so it moves instead of hanging flat.',
    maintenance: 'Medium',
    bestFor: ['Oval', 'Round', 'Long'],
    popularity: 92,
    adjustments: ['length', 'color'],
    shape: shape(0.26, 0.95, 0.92, 0.25, 'straight', { part: 'middle' }),
    defaultColorId: 'espresso',
  },
  {
    id: 'beach-waves',
    name: 'Beach Waves',
    categoryIds: ['long', 'wavy'],
    genders: ['female'],
    tags: ['relaxed', 'summer'],
    description: 'Loose, undone S-waves through the length. Looks effortless, takes forty minutes.',
    maintenance: 'Medium',
    bestFor: ['Oval', 'Square', 'Heart'],
    popularity: 95,
    adjustments: ['length', 'color'],
    shape: shape(0.34, 0.95, 0.88, 0.22, 'wavy', { part: 'middle' }),
    defaultColorId: 'caramel',
  },
  {
    id: 'sleek-straight',
    name: 'Sleek & Straight',
    categoryIds: ['long', 'straight'],
    genders: ['female'],
    tags: ['polished', 'glossy'],
    description: 'Pressed flat and glossy from root to tip with a razor-clean centre part.',
    maintenance: 'High',
    bestFor: ['Oval', 'Heart'],
    popularity: 80,
    adjustments: ['length', 'color'],
    shape: shape(0.14, 1, 0.95, 0.2, 'straight', { part: 'middle' }),
    defaultColorId: 'jet',
  },
  {
    id: 'shoulder-flow',
    name: 'Shoulder Flow',
    categoryIds: ['long', 'wavy'],
    genders: ['male'],
    tags: ['grown out', 'relaxed'],
    description: 'Grown-out length swept back off the face and falling to the shoulders.',
    maintenance: 'Medium',
    bestFor: ['Oval', 'Square'],
    popularity: 72,
    adjustments: ['length', 'color'],
    shape: shape(0.4, 0.8, 0.6, 0.1, 'wavy', { part: 'middle' }),
    defaultColorId: 'chestnut',
  },
  {
    id: 'man-bun',
    name: 'Man Bun',
    categoryIds: ['long', 'updo'],
    genders: ['male'],
    tags: ['tied back', 'practical'],
    description: 'Long hair gathered and knotted at the back of the crown, sides left down or faded.',
    maintenance: 'Low',
    bestFor: ['Oval', 'Square'],
    popularity: 68,
    adjustments: ['fade', 'color'],
    shape: shape(0.3, 0.3, 0.12, 0.08, 'straight', { knot: true }),
    defaultColorId: 'espresso',
  },
  {
    id: 'top-knot',
    name: 'Top Knot',
    categoryIds: ['updo', 'trendy'],
    genders: ['male', 'female'],
    tags: ['tied back', 'sharp sides'],
    description: 'Everything on top pulled up into a knot above shaved or faded sides.',
    maintenance: 'Medium',
    bestFor: ['Oval', 'Diamond'],
    popularity: 66,
    adjustments: ['fade', 'color'],
    shape: shape(0.26, 0.06, 0, 0.05, 'straight', { knot: true }),
    defaultColorId: 'jet',
  },
  {
    id: 'curly-top',
    name: 'Curly Top',
    categoryIds: ['curly', 'medium'],
    genders: ['male'],
    tags: ['natural curl', 'volume'],
    description: 'Curls left long on top with the sides cut back so the curl pattern reads clearly.',
    maintenance: 'Medium',
    bestFor: ['Oval', 'Square'],
    popularity: 87,
    adjustments: ['length', 'fade', 'color'],
    shape: shape(0.62, 0.16, 0, 0.3, 'curly'),
    defaultColorId: 'espresso',
  },
  {
    id: 'afro',
    name: 'Afro',
    categoryIds: ['curly', 'trendy'],
    genders: ['male', 'female'],
    tags: ['natural', 'volume', 'statement'],
    description: 'Coils grown out evenly in every direction and shaped into a round silhouette.',
    maintenance: 'Medium',
    bestFor: ['Oval', 'Square', 'Heart'],
    popularity: 83,
    adjustments: ['length', 'color'],
    shape: shape(0.95, 0.55, 0.1, 0.2, 'coily'),
    defaultColorId: 'jet',
  },
  {
    id: 'twist-out',
    name: 'Twist Out',
    categoryIds: ['curly', 'medium'],
    genders: ['female', 'male'],
    tags: ['natural', 'defined coils'],
    description: 'Two-strand twists taken down for defined, springy coils with plenty of body.',
    maintenance: 'Medium',
    bestFor: ['Oval', 'Round'],
    popularity: 84,
    adjustments: ['length', 'color'],
    shape: shape(0.72, 0.62, 0.24, 0.28, 'coily'),
    defaultColorId: 'espresso',
  },
  {
    id: 'curly-shag',
    name: 'Curly Shag',
    categoryIds: ['curly', 'trendy', 'medium'],
    genders: ['female'],
    tags: ['layered', 'rock'],
    description: 'Heavy layering through curly hair with a full fringe. Deliberately shaggy.',
    maintenance: 'Medium',
    bestFor: ['Oval', 'Long'],
    popularity: 88,
    adjustments: ['length', 'color'],
    shape: shape(0.58, 0.8, 0.55, 0.7, 'curly'),
    defaultColorId: 'auburn',
  },
  {
    id: 'loose-curls',
    name: 'Loose Curls',
    categoryIds: ['curly', 'long'],
    genders: ['female'],
    tags: ['soft', 'romantic'],
    description: 'Wide barrel curls through long hair, brushed out so they fall soft rather than tight.',
    maintenance: 'Medium',
    bestFor: ['Oval', 'Square', 'Heart'],
    popularity: 90,
    adjustments: ['length', 'color'],
    shape: shape(0.44, 0.95, 0.85, 0.25, 'curly', { part: 'side' }),
    defaultColorId: 'chestnut',
  },
  {
    id: 'wolf-cut',
    name: 'Wolf Cut',
    categoryIds: ['trendy', 'wavy', 'medium'],
    genders: ['female', 'male'],
    tags: ['layered', 'internet famous'],
    description: 'A shag and a mullet met halfway: heavy top layers, wispy ends, plenty of attitude.',
    maintenance: 'Medium',
    bestFor: ['Oval', 'Round'],
    popularity: 89,
    adjustments: ['length', 'color'],
    shape: shape(0.55, 0.7, 0.62, 0.68, 'wavy'),
    defaultColorId: 'smoke',
  },
  {
    id: 'butterfly-cut',
    name: 'Butterfly Cut',
    categoryIds: ['trendy', 'long', 'wavy'],
    genders: ['female'],
    tags: ['face framing', 'bouncy'],
    description: 'Short face-framing layers over long length, so it reads as two haircuts at once.',
    maintenance: 'Medium',
    bestFor: ['Oval', 'Long', 'Square'],
    popularity: 93,
    adjustments: ['length', 'color'],
    shape: shape(0.5, 0.92, 0.8, 0.42, 'wavy', { part: 'middle' }),
    defaultColorId: 'honey',
  },
  {
    id: 'modern-mullet',
    name: 'Modern Mullet',
    categoryIds: ['trendy', 'medium'],
    genders: ['male', 'female'],
    tags: ['bold', 'retro revival'],
    description: 'Short and tight at the front and sides, deliberately long at the back.',
    maintenance: 'Medium',
    bestFor: ['Oval', 'Diamond'],
    popularity: 71,
    adjustments: ['length', 'fade', 'color'],
    shape: shape(0.4, 0.18, 0.55, 0.35, 'wavy'),
    defaultColorId: 'chestnut',
  },
  {
    id: 'mohawk',
    name: 'Mohawk',
    categoryIds: ['trendy', 'fades'],
    genders: ['male', 'female'],
    tags: ['statement', 'shaved sides'],
    description: 'A strip of length down the centre with everything either side taken to the skin.',
    maintenance: 'High',
    bestFor: ['Oval', 'Long'],
    popularity: 55,
    adjustments: ['fade', 'color'],
    shape: shape(0.9, 0.02, 0, 0.1, 'spiky'),
    defaultColorId: 'jet',
  },
  {
    id: 'box-braids',
    name: 'Box Braids',
    categoryIds: ['updo', 'long'],
    genders: ['female', 'male'],
    tags: ['protective', 'long lasting'],
    description: 'Sectioned braids installed to the length you want, low effort once they are in.',
    maintenance: 'Low',
    bestFor: ['Oval', 'Round', 'Heart'],
    popularity: 86,
    adjustments: ['length', 'color'],
    shape: shape(0.3, 0.95, 0.9, 0.2, 'coily', { part: 'middle' }),
    defaultColorId: 'jet',
  },
  {
    id: 'high-ponytail',
    name: 'High Ponytail',
    categoryIds: ['updo', 'straight'],
    genders: ['female'],
    tags: ['sleek', 'quick'],
    description: 'Everything pulled up tight and gathered high at the crown.',
    maintenance: 'Low',
    bestFor: ['Oval', 'Heart', 'Round'],
    popularity: 77,
    adjustments: ['length', 'color'],
    shape: shape(0.2, 0.12, 0.6, 0.1, 'straight', { tail: true }),
    defaultColorId: 'espresso',
  },
  {
    id: 'slick-back',
    name: 'Slick Back',
    categoryIds: ['medium', 'straight', 'trendy'],
    genders: ['male'],
    tags: ['sharp', 'formal'],
    description: 'Everything combed straight back off the face with product holding it in place.',
    maintenance: 'Medium',
    bestFor: ['Oval', 'Square', 'Diamond'],
    popularity: 83,
    adjustments: ['length', 'fade', 'color'],
    shape: shape(0.45, 0.26, 0.12, 0.0, 'straight'),
    defaultColorId: 'jet',
  },
];

const highlights = [
  'Try any hairstyle on your own photo in seconds',
  'Neutral mannequin previews keep the focus on the cut',
  'Adjust length, fade and colour before you commit',
  'Compare before and after side by side',
  'Save the looks you like and take them to your barber',
];

export const mockCatalog: Catalog = {
  categories,
  colors,
  highlights,
  hairstyles: hairstyles.map((row) => ({ ...row, imageUrl: null })),
};
