/**
 * Keeps the app's hair-type example map in step with what is on disk.
 *
 * Same bridge as `lib/renders.mjs` builds for the catalog, and for the same
 * reason: Metro only bundles an asset some module `require`s by a literal path,
 * so "a PNG exists" only becomes "the picker shows it" once this module has been
 * rewritten from the directory listing.
 *
 * Much smaller than the catalog's, because the set is: two genders × four types,
 * and no masks. These images are never colour-graded — they illustrate what hair
 * *does*, not what a haircut would look like in a shade, so there is nothing to
 * hold a grade to and no mask to compute.
 */

import { readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { HAIR_TYPE_CELLS } from './hairTypeSheet.mjs';

export const EXAMPLE_GENDERS = ['male', 'female'];

const MODULE_PATH = ['src', 'api', 'hairTypeExamples.generated.ts'];

/** `male-coily.png`. The generated `<gender>-sheet.png` is not an example. */
const FILE_PATTERN = new RegExp(`^(${EXAMPLE_GENDERS.join('|')})-(${HAIR_TYPE_CELLS.join('|')})\.png$`);

/** Reads `<out>` and returns `{ [gender]: { [hairType]: absolutePath } }`. */
export async function scanExamples(out) {
  const examples = {};
  let files;
  try {
    files = await readdir(out);
  } catch {
    return examples;
  }

  for (const file of files.sort()) {
    const match = FILE_PATTERN.exec(file);
    if (!match) continue;
    const [, gender, type] = match;
    (examples[gender] ??= {})[type] = path.join(out, file);
  }
  return examples;
}

function render(examples, modulePath) {
  const requirePath = (file) => {
    const rel = path.relative(path.dirname(modulePath), file).split(path.sep).join('/');
    return rel.startsWith('.') ? rel : `./${rel}`;
  };

  const body = EXAMPLE_GENDERS.filter((gender) => examples[gender])
    .map((gender) => {
      const rows = HAIR_TYPE_CELLS.filter((type) => examples[gender][type])
        .map((type) => `    ${type}: require('${requirePath(examples[gender][type])}'),`)
        .join('\n');
      return rows ? `  ${gender}: {\n${rows}\n  },` : '';
    })
    .filter(Boolean)
    .join('\n');

  return `/**
 * AUTO-GENERATED by scripts/generate-hair-type-examples.mjs — do not edit by hand.
 *
 * One entry per hair-type example sitting in assets/hair-types/. Regenerate with:
 *
 *   npm run hair-types:sync
 *
 * (the generator and every \`npm start\` do it for you). Metro can only bundle an
 * asset some module requires by a literal path, which is why this file is code
 * rather than data — it is derived from the directory listing, holds no
 * judgement about any hair type, and is read only through
 * \`hairTypeExample()\` in src/lib/hairTypeExample.ts.
 *
 * These are the picker's texture examples, not catalog imagery: one head per
 * gender wearing the same plain hair in each of the four patterns, at the
 * length that gender wears it.
 * They are shown as generated and are never colour-graded.
 */

import type { Gender, HairTypeId } from './types';

/** What \`require()\` gives back for a bundled image: an asset registry handle. */
export type ExampleSource = number;

/** Keyed by gender, then hair type — both sides may be missing entries. */
export const hairTypeExamples: Partial<Record<Gender, Partial<Record<HairTypeId, ExampleSource>>>> = {${
    body ? `\n${body}\n` : ''
  }};
`;
}

/**
 * Rewrites the example module from whatever is currently in `out`, leaving the
 * file untouched when nothing changed so Metro does not reload for nothing.
 *
 * @param {{ root: string, out: string }} opts
 */
export async function writeExampleModule({ root, out }) {
  const modulePath = path.join(root, ...MODULE_PATH);
  const examples = await scanExamples(out);
  const source = render(examples, modulePath);

  const previous = await readFile(modulePath, 'utf8').catch(() => null);
  if (previous !== source) await writeFile(modulePath, source, 'utf8');

  const images = Object.values(examples).reduce((total, byType) => total + Object.keys(byType).length, 0);

  return {
    file: modulePath,
    relativeFile: path.relative(root, modulePath).split(path.sep).join('/'),
    genders: Object.keys(examples).length,
    images,
    changed: previous !== source,
  };
}
