/**
 * Keeps the app's render map in step with what is on disk.
 *
 * The generator writes PNGs into `assets/mannequins/<style>/<gender>-<angle>.png`,
 * but Metro only bundles an asset that some module actually `require`s, and a
 * require path has to be a literal. So the bridge between "a file exists" and
 * "the UI shows it" is this module: it scans the output directory and rewrites
 * `src/api/mannequinRenders.generated.ts` with one require per file.
 *
 * It runs at the end of every generator run (and on `npm start`), so a finished
 * style appears in the app on its own — Metro sees the regenerated module,
 * fast-refreshes, and `<Mannequin>` starts preferring the render over the
 * procedural drawing. Styles generated earlier stay in the map: it is rebuilt
 * from the whole directory every time, never appended to.
 *
 * Hair masks are part of that bridge. A render is only fully usable once the app
 * can tell hair from mannequin in it — the colour grade has to stay off the head
 * — so any render whose mask is missing or older than it gets one computed here,
 * before the module that points at it is written. That keeps "what is on disk is
 * what the app shows" true for masks as well as renders.
 */

import { readFile, readdir, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { hairMask } from './hairMask.mjs';
import { decodePng, encodePng } from './png.mjs';
import { SHEET } from './sheet.mjs';

/** The angles the app can display — the sheet's panels, in sheet order. */
export const RENDER_ANGLES = SHEET.cells;
export const RENDER_GENDERS = ['male', 'female'];

/**
 * `male-half.png` and friends. The composed `<gender>-sheet.png` is not a view,
 * and neither is `male-half-mask.png` — the anchored `.png` excludes both.
 */
const FILE_PATTERN = new RegExp(`^(${RENDER_GENDERS.join('|')})-(${RENDER_ANGLES.join('|')})\.png$`);

const MODULE_PATH = ['src', 'api', 'mannequinRenders.generated.ts'];

/** `male-half.png` -> `male-half-mask.png`. */
export const maskFileFor = (file) => file.replace(/\.png$/, '-mask.png');

/** Directory name -> hairstyle id. `_base` and other underscore dirs are not styles. */
const isStyleDir = (entry) => entry.isDirectory() && !entry.name.startsWith('_') && !entry.name.startsWith('.');

/**
 * Reads `<out>` and returns `{ [styleId]: { [gender]: { [angle]: absolutePath } } }`,
 * with only the files that actually exist.
 */
export async function scanRenders(out) {
  const styles = {};
  let entries;
  try {
    entries = await readdir(out, { withFileTypes: true });
  } catch {
    return styles;
  }

  for (const entry of entries.filter(isStyleDir).sort((a, b) => a.name.localeCompare(b.name))) {
    const dir = path.join(out, entry.name);
    const files = (await readdir(dir)).sort();
    for (const file of files) {
      const match = FILE_PATTERN.exec(file);
      if (!match) continue;
      const [, gender, angle] = match;
      ((styles[entry.name] ??= {})[gender] ??= {})[angle] = path.join(dir, file);
    }
  }
  return styles;
}

function render(styles, modulePath, masksOnDisk) {
  const requirePath = (file) => {
    const rel = path.relative(path.dirname(modulePath), file).split(path.sep).join('/');
    return rel.startsWith('.') ? rel : `./${rel}`;
  };

  /**
   * Both maps have the same shape and the same gaps, so they are built by the
   * same walk: `fileFor` turns a render path into the path to require, or null
   * to leave that view out.
   */
  const mapOf = (fileFor) =>
    Object.keys(styles)
      .map((id) => {
        const variants = RENDER_GENDERS.filter((gender) => styles[id][gender])
          .map((gender) => {
            const views = RENDER_ANGLES.filter((angle) => styles[id][gender][angle])
              .map((angle) => [angle, fileFor(styles[id][gender][angle])])
              .filter(([, file]) => file)
              .map(([angle, file]) => `      ${angle}: require('${requirePath(file)}'),`)
              .join('\n');
            return views ? `    ${gender}: {\n${views}\n    },` : '';
          })
          .filter(Boolean)
          .join('\n');
        return variants ? `  '${id}': {\n${variants}\n  },` : '';
      })
      .filter(Boolean)
      .join('\n');

  const body = mapOf((file) => file);
  const masks = mapOf((file) => (masksOnDisk.has(maskFileFor(file)) ? maskFileFor(file) : null));

  return `/**
 * AUTO-GENERATED by scripts/generate-mannequins.mjs — do not edit by hand.
 *
 * One entry per mannequin render sitting in assets/mannequins/. Regenerate with:
 *
 *   npm run mannequins:sync
 *
 * (every generator run and every \`npm start\` does it for you). Metro can only
 * bundle an asset some module requires by a literal path, which is why this file
 * is code rather than data — it is derived from the directory listing, holds no
 * judgement about any hairstyle, and is read only through
 * \`mannequinRender()\` in src/lib/mannequinRender.ts.
 *
 * These are the local, ahead-of-time catalog renders. The backend's own
 * \`hairstyle.imageUrl\` still wins over them when it is populated.
 */

import type { Gender } from './types';
import type { ViewAngle } from '@/lib/hairShape';

/** What \`require()\` gives back for a bundled image: an asset registry handle. */
export type RenderSource = number;

export type MannequinRenderMap = Partial<Record<Gender, Partial<Record<ViewAngle, RenderSource>>>>;

/** Keyed by hairstyle id — the app never reads a name out of here. */
export const mannequinRenders: Record<string, MannequinRenderMap> = {${body ? `\n${body}\n` : ''}};

/**
 * The matching hair masks: greyscale, white where the haircut is, the same size
 * as the render they belong to. Written by \`scripts/generate-hair-masks.mjs\`
 * and used to keep the colour grade off the mannequin. A render missing from
 * here is graded whole, which is the old behaviour rather than a broken one.
 */
export const mannequinMasks: Record<string, MannequinRenderMap> = {${masks ? `\n${masks}\n` : ''}};
`;
}

/**
 * Rewrites the render module from whatever is currently in `out`.
 * Leaves the file untouched when nothing changed, so Metro does not reload for
 * a run that generated nothing.
 *
 * Calls are serialised: the generator syncs after every finished style so a long
 * run drops each haircut into the running app as it lands, and two workers
 * finishing at once must not write the file over each other.
 *
 * @param {{ root: string, out: string }} opts
 */
export function writeRenderModule(opts) {
  queue = queue.then(
    () => rewrite(opts),
    () => rewrite(opts),
  );
  return queue;
}

/** Serialises `rewrite` — see `writeRenderModule`. */
let queue = Promise.resolve();

async function rewrite({ root, out }) {
  const modulePath = path.join(root, ...MODULE_PATH);
  const styles = await scanRenders(out);

  const files = Object.values(styles).flatMap((byGender) =>
    Object.values(byGender).flatMap((views) => Object.values(views)),
  );
  const masked = await ensureHairMasks(files);
  const masksOnDisk = new Set(masked.filter((entry) => entry.mask).map((entry) => entry.mask));

  const source = render(styles, modulePath, masksOnDisk);

  const previous = await readFile(modulePath, 'utf8').catch(() => null);
  if (previous !== source) await writeFile(modulePath, source, 'utf8');

  const images = Object.values(styles).reduce(
    (total, byGender) => total + Object.values(byGender).reduce((n, views) => n + Object.keys(views).length, 0),
    0,
  );

  return {
    file: modulePath,
    relativeFile: path.relative(root, modulePath).split(path.sep).join('/'),
    styles: Object.keys(styles).length,
    images,
    masks: masksOnDisk.size,
    maskedNow: masked.filter((entry) => entry.written).length,
    changed: previous !== source,
  };
}

/**
 * Makes sure every render has an up-to-date hair mask beside it.
 *
 * A mask is rebuilt only when it is missing or older than its render, so this is
 * one stat per file on a warm catalog and a few tens of milliseconds per new
 * render. A failure is reported, never thrown: a render whose mask could not be
 * computed still belongs in the app, it is simply graded whole.
 *
 * @param {string[]} files render paths
 * @param {{ force?: boolean }} [opts]
 */
export async function ensureHairMasks(files, { force = false } = {}) {
  return Promise.all(files.map((file) => ensureOneMask(file, force)));
}

async function ensureOneMask(file, force) {
  const mask = maskFileFor(file);

  if (!force) {
    const [source, existing] = await Promise.all([
      stat(file).catch(() => null),
      stat(mask).catch(() => null),
    ]);
    if (existing && source && existing.mtimeMs >= source.mtimeMs) return { file, mask, written: false };
  }

  try {
    const { mask: image, coverage } = hairMask(decodePng(await readFile(file)));
    await writeFile(mask, encodePng(image));
    return { file, mask, written: true, coverage };
  } catch (error) {
    console.warn(`  ! could not mask ${path.basename(file)}: ${error.message}`);
    return { file, mask: null, written: false };
  }
}
