-- The hair-type picker's own imagery.
--
-- Not catalog imagery, and deliberately a separate table rather than a column on
-- `hair_types`: an example is per gender x type, because a type 4 coil on a
-- feminine head is a different picture from the same coil on a masculine one and
-- the user has already said which they are. A `hair_types` row is per type only,
-- so a column there could hold one of the two and would silently pick a side.
--
-- These are generated by scripts/generate-hair-type-examples.mjs — two 2x2
-- sheets, one per gender, cut into four — and they go through the same
-- content-addressed pipeline as the mannequin renders. What they do *not* share
-- is masks or the colour grade: an example of a texture has no shade to be put
-- in, so there is no mask column here and never should be.
create table if not exists hair_type_examples (
  hair_type_id    text not null references hair_types (id),
  gender          text not null,
  url             text not null,
  width           integer not null,
  height          integer not null,
  bytes           integer not null,
  source_checksum text not null,
  updated_at      timestamptz not null default now(),
  primary key (hair_type_id, gender),
  constraint hair_type_examples_gender_domain check (gender in ('male', 'female'))
);
