#!/usr/bin/env node
/**
 * Copies the app modules the server has to run itself.
 *
 *   node scripts/sync-shared.mjs           write server/src/generated/
 *   node scripts/sync-shared.mjs --check   fail if they are out of date
 *
 * ## Why a copy and not an import
 *
 * The app and the server are separate programs and neither may import across the
 * boundary — the rule that makes `scripts/lib/variants.mjs` a mirror of
 * `src/lib/hairTypes.ts` rather than a shared module. It is not only taste here:
 * Railway deploys with the root directory set to `server/`, so `../src` does not
 * exist in the deployment at all.
 *
 * ## Why a copy and not a mirror
 *
 * Everything else in this repo that crosses the boundary is a *hand-written*
 * mirror, kept honest by a round-trip check. That bargain works for predicates —
 * two implementations of "is this cut offered for type 4" can be compared by
 * running them. It fails completely for `tryOnPrompt.ts`, which is authored
 * English prose that the product owner edits as prose: two copies of a prompt
 * that have drifted apart are two different haircuts, and no test can tell you
 * which of them is the one that was meant.
 *
 * So these are generated, mechanically, from the single authored source, and
 * `--check` runs in `npm run check` so a stale copy fails the build rather than
 * shipping. Edit `src/lib/tryOnPrompt.ts`. Never edit the output.
 *
 * The only thing the transform changes is the import header: the app's files
 * import their types through the `@/` alias, which resolves to `src/`, and the
 * server has its own mirror of those types. Everything below the imports is
 * copied byte for byte, and a *value* import — anything the transform cannot
 * honestly re-point — is a hard error rather than a guess.
 */

import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const SERVER_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const REPO_ROOT = path.resolve(SERVER_ROOT, '..');
const OUT_DIR = path.join(SERVER_ROOT, 'src', 'generated');

/**
 * `imageSize.ts` has no imports at all — deliberately, and it says so in its own
 * header, because `scripts/try-on.mjs` already loads it through
 * `lib/transpile.mjs`. It copies verbatim.
 *
 * `legal.ts` is here for exactly the reason `tryOnPrompt.ts` is, one step
 * further along: the Privacy Policy and the Terms of Use are authored prose, the
 * app renders them as screens and the server serves the same words at /privacy
 * and /terms for the two store listings, and two copies of a privacy policy that
 * have drifted apart are two different promises about somebody's photograph.
 */
const SOURCES = ['src/lib/imageSize.ts', 'src/lib/tryOnPrompt.ts', 'src/lib/legal.ts'];

const TYPE_IMPORT = /^import type \{([^}]*)\} from '@\/[^']*';$/;
const VALUE_IMPORT = /^import (?!type )/;

/**
 * One app module as the server should see it.
 *
 * @param {string} relative  path from the repo root
 * @param {string} source    the file's text
 */
function transpose(relative, source) {
  const lines = source.split('\n');
  const named = new Set();
  const body = [];

  for (const line of lines) {
    const typeImport = TYPE_IMPORT.exec(line.trim());
    if (typeImport) {
      for (const name of typeImport[1].split(',')) {
        const trimmed = name.trim();
        if (trimmed) named.add(trimmed);
      }
      continue;
    }
    if (VALUE_IMPORT.test(line.trim())) {
      throw new Error(
        `${relative} has a value import (${line.trim()}). ` +
          'Only type-only imports can be re-pointed at the server\'s own types — ' +
          'either keep the module import-free or mirror it by hand.',
      );
    }
    body.push(line);
  }

  const banner = [
    '// Generated by server/scripts/sync-shared.mjs — DO NOT EDIT.',
    `// Source of truth: ${relative}`,
    '//',
    '// The app and the server run the same prompt and the same output-size',
    '// arithmetic. Edit the source above and run `npm run sync:shared`;',
    '// `npm run check` fails if this file is behind.',
    '',
  ];
  const imports = named.size
    ? [`import type { ${[...named].sort().join(', ')} } from '../types.js';`, '']
    : [];

  // Only the blank lines the removed imports left behind are trimmed. Everything
  // from the first real line down is untouched, which is what makes "byte for
  // byte below the header" a claim anyone can check with a diff.
  while (body.length && !body[0].trim()) body.shift();
  return [...banner, ...imports, ...body].join('\n');
}

const check = process.argv.includes('--check');
await mkdir(OUT_DIR, { recursive: true });

let stale = 0;
for (const relative of SOURCES) {
  const source = await readFile(path.join(REPO_ROOT, relative), 'utf8');
  const output = transpose(relative, source);
  const target = path.join(OUT_DIR, path.basename(relative));

  const existing = await readFile(target, 'utf8').catch(() => null);
  if (existing === output) continue;

  if (check) {
    console.error(`  ! server/src/generated/${path.basename(relative)} is out of date with ${relative}`);
    stale += 1;
    continue;
  }
  await writeFile(target, output, 'utf8');
  console.log(`  wrote src/generated/${path.basename(relative)}`);
}

// A file left behind after its source was removed from SOURCES is worse than a
// stale one: it still compiles, and nothing points at what it came from.
const orphans = (await readdir(OUT_DIR).catch(() => [])).filter(
  (file) => file.endsWith('.ts') && !SOURCES.some((relative) => path.basename(relative) === file),
);
for (const orphan of orphans) console.error(`  ! src/generated/${orphan} has no source in SOURCES`);

if (check && (stale || orphans.length)) {
  console.error('\nRun `npm run sync:shared` from server/, and commit the result.');
  process.exit(1);
}
if (!check) console.log(stale + orphans.length ? '' : 'Shared modules are up to date.');
